/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Inventario;

import Modelo.Inventario;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author David
 */
public class Dialogo_Imagen_Producto extends javax.swing.JDialog {

    /**
     * Creates new form Dialogo_Imagen_Producto
     */
    public Dialogo_Imagen_Producto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
    }
    
    public void mostrar_Imagen(Inventario inventario) {
        try {
            Image foto = getToolkit().createImage(inventario.getImagen());
            foto = foto.getScaledInstance(500, 400, Image.SCALE_DEFAULT);
            this.set_Campos_Producto(inventario);
            this.etiqueta_Imagen.setIcon(new ImageIcon(foto));
            this.setVisible(true);
        } catch (Exception ex) {
        }
    }
    
    public void set_Campos_Producto(Inventario inventario){
        this.campo_Codigo.setText(inventario.getCodigo());
        this.campo_Descripcion.setText(inventario.getDescripcion());
        this.campo_Cantidad.setText(String.valueOf(inventario.getCantidad_Disponible()));
        this.campo_Precio.setText(String.valueOf(inventario.getPrecio_Venta()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiqueta_Imagen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campo_Codigo = new javax.swing.JTextField();
        campo_Descripcion = new javax.swing.JTextField();
        campo_Cantidad = new javax.swing.JTextField();
        campo_Precio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Producto");
        setMaximumSize(new java.awt.Dimension(500, 597));
        setMinimumSize(new java.awt.Dimension(500, 597));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiqueta_Imagen.setMaximumSize(new java.awt.Dimension(500, 500));
        etiqueta_Imagen.setMinimumSize(new java.awt.Dimension(500, 500));
        etiqueta_Imagen.setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().add(etiqueta_Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Codigo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Descripcion:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Cantidad:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Precio de venta:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        campo_Codigo.setEditable(false);
        campo_Codigo.setBackground(new java.awt.Color(255, 255, 255));
        campo_Codigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        campo_Codigo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(campo_Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 180, 22));

        campo_Descripcion.setEditable(false);
        campo_Descripcion.setBackground(new java.awt.Color(255, 255, 255));
        campo_Descripcion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        campo_Descripcion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(campo_Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 290, 22));

        campo_Cantidad.setEditable(false);
        campo_Cantidad.setBackground(new java.awt.Color(255, 255, 255));
        campo_Cantidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        campo_Cantidad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(campo_Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 70, 22));

        campo_Precio.setEditable(false);
        campo_Precio.setBackground(new java.awt.Color(255, 255, 255));
        campo_Precio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        campo_Precio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(campo_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 70, 22));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo blanco  1.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 500, 197));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Imagen_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Imagen_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Imagen_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Imagen_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dialogo_Imagen_Producto dialog = new Dialogo_Imagen_Producto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campo_Cantidad;
    private javax.swing.JTextField campo_Codigo;
    private javax.swing.JTextField campo_Descripcion;
    private javax.swing.JTextField campo_Precio;
    public javax.swing.JLabel etiqueta_Imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
