/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Maquilas.Orden_De_Produccion;

import Modelo.Maquila;
import Modelo.Orden_Produccion;
import Modelo.Usuario;
import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author David
 */
public class Panel_Orden_De_Produccion extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Cotizacion
     */
    public Panel_Orden_De_Produccion() {
        initComponents();/*
        calendario_Orden.setDate( new Date() );
        tabla_Productos_Maquila.getTableHeader().setFont( new Font( "Segoe UI", Font.BOLD, 14 ) );
        tabla_Productos_Maquila.getTableHeader().setBackground( new Color( 32, 136, 203 ) );
        tabla_Productos_Maquila.getTableHeader().setForeground( new Color( 255, 255, 255) );*/
 
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        this.tabla_Consulta_Orden_Produccion.getColumnModel().getColumn(0).setCellRenderer(tcr);
        this.campo_Busqueda.setEditable(false);
/*
        this.tabla_Productos_Maquila.getColumnModel().getColumn(0).setCellRenderer(tcr);
        this.etiqueta_Indicador_Maquila.setVisible( false );
        this.etiqueta_Indicador_RUC.setVisible( false );
        this.etiqueta_Indicador_Direccion.setVisible( false );
        this.etiqueta_Indicador_Telefono.setVisible( false );
        this.etiqueta_Estado.setVisible( false );*/
this.fecha_1.setVisible(false);
        this.fecha_2.setVisible(false);
        this.boton_Fecha.setVisible(false);
        this.fecha_1.setDate( new Date() );
        this.fecha_2.setDate( new Date() );
        this.etiqueta_Error_Fecha.setVisible(false);
        this.boton_Modificar_Orden.setEnabled( false );
        //this.boton_Agregar_Fila.setEnabled( false );
        //this.boton_Quitar_Fila.setEnabled( false );
        this.boton_Generar_Orden.setEnabled(false);
        //this.etiqueta_Indicador_Calendario.setVisible(false);
        this.tabla_Consulta_Orden_Produccion.getTableHeader().setReorderingAllowed(false) ;
    }
    
    public void Roles(String rol) {
        if (rol.equals("Vendedor")) {
            boolean[] bandera = {false, false, false, false, false, false, false};
            this.habilitar_Rol(bandera);
        }

        if (rol.equals("Bodeguero")) {
            boolean[] bandera = {false, false, false, false, false, false, false};
            this.habilitar_Rol(bandera);
        }

        if (rol.equals("Contador")) {
            boolean[] bandera = {true, false, false, true, false, false, false};
            this.habilitar_Rol(bandera);
        }

        if (rol.equals("Administrador")) {
            System.out.println("administrador");
            boolean[] bandera = {true, false, false, true, false, false, false};
            this.habilitar_Rol(bandera);
        }
        
        if (rol.equals("Maquila")) {
            boolean[] bandera = {true, true, true, true, true, true, true};
            this.habilitar_Rol(bandera);
        }
    }
    
     public void habilitar_Rol(boolean[] bandera) {
        this.boton_Nueva_Orden.setVisible(bandera[0]);
        //this.boton_Guardar_Orden.setVisible(bandera[1]);
        this.boton_Modificar_Orden.setVisible(bandera[2]);
        this.boton_Generar_Orden.setVisible(bandera[3]);
       // this.boton_Agregar_Maquila.setVisible(bandera[4]);
       // this.boton_Agregar_Fila.setVisible(bandera[5]);
       // this.boton_Quitar_Fila.setVisible(bandera[6]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        boton_Nueva_Orden = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        boton_Modificar_Orden = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        boton_Generar_Orden = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        boton_Cerrar_Sesion = new javax.swing.JButton();
        etiqueta_Rol = new javax.swing.JLabel();
        etiqueta_Nombre_Usuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Consulta_Orden_Produccion = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        campo_Busqueda = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        fecha_1 = new com.toedter.calendar.JDateChooser();
        fecha_2 = new com.toedter.calendar.JDateChooser();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        etiqueta_Error_Fecha = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        boton_Fecha = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        combo_Opciones = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(239, 239, 239));
        setMaximumSize(new java.awt.Dimension(1400, 800));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setPreferredSize(new java.awt.Dimension(1400, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator1);

        boton_Nueva_Orden.setBackground(new java.awt.Color(255, 255, 255));
        boton_Nueva_Orden.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Nueva_Orden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-archivo.png"))); // NOI18N
        boton_Nueva_Orden.setText("Nuevo");
        boton_Nueva_Orden.setToolTipText("Nueva cotizacion");
        boton_Nueva_Orden.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Nueva_Orden.setFocusable(false);
        boton_Nueva_Orden.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Nueva_Orden.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Nueva_Orden.setMinimumSize(new java.awt.Dimension(100, 37));
        boton_Nueva_Orden.setPreferredSize(new java.awt.Dimension(100, 37));
        boton_Nueva_Orden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Nueva_OrdenActionPerformed(evt);
            }
        });
        jToolBar1.add(boton_Nueva_Orden);
        jToolBar1.add(jSeparator2);

        boton_Modificar_Orden.setBackground(new java.awt.Color(255, 255, 255));
        boton_Modificar_Orden.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Modificar_Orden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar-documento.png"))); // NOI18N
        boton_Modificar_Orden.setText("Modificar");
        boton_Modificar_Orden.setToolTipText("Modificar orden");
        boton_Modificar_Orden.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Modificar_Orden.setFocusable(false);
        boton_Modificar_Orden.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Modificar_Orden.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Modificar_Orden.setMinimumSize(new java.awt.Dimension(60, 37));
        boton_Modificar_Orden.setPreferredSize(new java.awt.Dimension(100, 37));
        jToolBar1.add(boton_Modificar_Orden);
        jToolBar1.add(jSeparator3);

        boton_Generar_Orden.setBackground(new java.awt.Color(255, 255, 255));
        boton_Generar_Orden.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Generar_Orden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportar 1.png"))); // NOI18N
        boton_Generar_Orden.setText("Generar");
        boton_Generar_Orden.setToolTipText("Generar orden");
        boton_Generar_Orden.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Generar_Orden.setFocusable(false);
        boton_Generar_Orden.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Generar_Orden.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Generar_Orden.setMinimumSize(new java.awt.Dimension(100, 37));
        boton_Generar_Orden.setPreferredSize(new java.awt.Dimension(100, 37));
        jToolBar1.add(boton_Generar_Orden);
        jToolBar1.add(jSeparator5);

        add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 800));

        boton_Cerrar_Sesion.setBackground(new java.awt.Color(255, 255, 255));
        boton_Cerrar_Sesion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Cerrar_Sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exit-32.png"))); // NOI18N
        boton_Cerrar_Sesion.setText("Cerrar");
        boton_Cerrar_Sesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(boton_Cerrar_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 120, 40));

        etiqueta_Rol.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        etiqueta_Rol.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(etiqueta_Rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(1134, 20, 147, 20));

        etiqueta_Nombre_Usuario.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        etiqueta_Nombre_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        etiqueta_Nombre_Usuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        etiqueta_Nombre_Usuario.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(etiqueta_Nombre_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 180, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo blanco.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 180, 40));

        tabla_Consulta_Orden_Produccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tabla_Consulta_Orden_Produccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No_Orden", "Maquila", "RUC / CI", "Fecha", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_Consulta_Orden_Produccion);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 1300, 760));

        jToolBar2.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar2.setRollover(true);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        jLabel1.setText("    ");
        jToolBar2.add(jLabel1);

        campo_Busqueda.setEditable(false);
        campo_Busqueda.setBackground(new java.awt.Color(255, 255, 255));
        campo_Busqueda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Busqueda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Busqueda.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        campo_Busqueda.setMaximumSize(new java.awt.Dimension(450, 30));
        campo_Busqueda.setMinimumSize(new java.awt.Dimension(450, 30));
        campo_Busqueda.setPreferredSize(new java.awt.Dimension(440, 30));
        jToolBar2.add(campo_Busqueda);
        jToolBar2.add(jSeparator4);

        fecha_1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Desde", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jToolBar2.add(fecha_1);

        fecha_2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hasta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jToolBar2.add(fecha_2);
        jToolBar2.add(jSeparator6);

        etiqueta_Error_Fecha.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etiqueta_Error_Fecha.setForeground(new java.awt.Color(204, 0, 51));
        etiqueta_Error_Fecha.setText("*");
        jToolBar2.add(etiqueta_Error_Fecha);
        jToolBar2.add(jSeparator7);

        boton_Fecha.setBackground(new java.awt.Color(255, 255, 255));
        boton_Fecha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Fecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/busqueda (1).png"))); // NOI18N
        boton_Fecha.setText("Buscar");
        boton_Fecha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Fecha.setMaximumSize(new java.awt.Dimension(75, 40));
        boton_Fecha.setMinimumSize(new java.awt.Dimension(75, 40));
        boton_Fecha.setPreferredSize(new java.awt.Dimension(75, 40));
        jToolBar2.add(boton_Fecha);
        jToolBar2.add(jSeparator8);

        combo_Opciones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combo_Opciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione.....", "Por numero", "Por nombre", "Por RUC", "Por fecha" }));
        combo_Opciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar2.add(combo_Opciones);

        add(jToolBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 1000, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void boton_Nueva_OrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Nueva_OrdenActionPerformed

    }//GEN-LAST:event_boton_Nueva_OrdenActionPerformed
/*
    public void valores_Maquila( String maquila, String direccion, String telefono, String RUC ){
        this.combo_Maquila_Orden.setText(maquila);
        this.campo_Direccion_Orden.setText( direccion );
        this.campo_Telefono_Orden.setText( telefono );
        this.campo_RUC_Orden.setText( RUC );
    }
*/    
  /*  public void valores_Orden( String estado, double valor_Total, String no_Factura, String observaciones ){
        this.combo_Estado_Orden.setSelectedItem( estado );
        this.campo_Total_Orden.setText( String.valueOf( valor_Total ) );
        this.etiqueta_No_Orden.setText( no_Factura );
        this.caja_Observaciones_Maquila.setText( observaciones );
    }*/
    /*
    public void valores_Tabla_Orden(Orden_Produccion lista_Orden, Maquila maquila){
        DefaultTableModel modelo_Tabla_Orden = ( DefaultTableModel )  this.tabla_Productos_Maquila.getModel();
        modelo_Tabla_Orden.setRowCount(0);
        
        String[] cantidad = lista_Orden.getCantidad().split(";");
        String[] descripcion = lista_Orden.getDescripcion().split(";");
        String[] v_Unitario = lista_Orden.getV_Unitario().split(";");
        String[] v_Total = lista_Orden.getV_Total().split(";");

        for (int i = 0; i < cantidad.length - 1; i++) {
            Object[] valores_Tabla = {cantidad[i], descripcion[i], Double.parseDouble(v_Unitario[i]), Double.parseDouble(v_Total[i])};
            modelo_Tabla_Orden.addRow(valores_Tabla);
        }
        this.valores_Maquila(maquila.getMaquila(), maquila.getDireccion(), maquila.getTelefono(), maquila.getRUC());
        this.valores_Orden(lista_Orden.getEstado(), lista_Orden.getV_Pagar(), lista_Orden.getNumero_Orden(), lista_Orden.getObservaciones());  
    }*/
    /*
    public boolean etiquetas( ){
        boolean bandera = true;
        if( this.combo_Maquila_Orden.getText().isEmpty() ){
            this.etiqueta_Indicador_Maquila.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Maquila.setVisible( false );
        }
        
        if (this.calendario_Orden.getDate() == null) {
            this.etiqueta_Indicador_Calendario.setVisible(bandera);
            bandera = false;
        }else{
            this.etiqueta_Indicador_Calendario.setVisible(false);
        }
            
        if( this.campo_RUC_Orden.getText().matches( "[0-9][0-9]{12}" ) ){
            this.etiqueta_Indicador_RUC.setVisible( false );
        }else if(this.campo_RUC_Orden.getText().matches( "[0-9][0-9]{9}" )){
            this.etiqueta_Indicador_RUC.setVisible( false );
        }
        else{
            this.etiqueta_Indicador_RUC.setVisible( true );
            bandera = false;
        }
            
        if( this.campo_Direccion_Orden.getText().isEmpty() ){ 
            this.etiqueta_Indicador_Direccion.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Direccion.setVisible( false );
        }
            
        if( this.campo_Telefono_Orden.getText().matches( "[0][1-9][0-9]{7}" ) ){
            this.etiqueta_Indicador_Telefono.setVisible( false );
        }else{
            this.etiqueta_Indicador_Telefono.setVisible( true );
            bandera = false;
        } 
        
        if( this.combo_Estado_Orden.getSelectedItem().equals( "Seleccionar.........." ) ){ 
            this.etiqueta_Estado.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Estado.setVisible( false );
        }
        
        return bandera;
    }*/
  /*  
    public String[] evaluar_Tabla(){
        DefaultTableModel modelo_Tabla_Maquila = ( DefaultTableModel ) this.tabla_Productos_Maquila.getModel();
        int verificar = 0;
        String[] valores = new String[5];
            
            for( int i = 0; i< modelo_Tabla_Maquila.getRowCount(); i++ ){
                if( modelo_Tabla_Maquila.getValueAt( i, 3 ) != null && ( double ) modelo_Tabla_Maquila.getValueAt( i, 3 ) > 0  ){
                    valores[0] = modelo_Tabla_Maquila.getValueAt( i, 0 ) + ";" + valores[0];
                    valores[1] = modelo_Tabla_Maquila.getValueAt( i, 1 ) + ";" + valores[1];
                    valores[2] = modelo_Tabla_Maquila.getValueAt( i, 2 ) + ";" + valores[2];
                    valores[3] = modelo_Tabla_Maquila.getValueAt( i, 3 ) + ";" + valores[3];
                    verificar++;
                }else{    
                }
            }
            valores[4] = String.valueOf( verificar );
            return valores;
    }*/
    /*
    public void limpiar_Valores(){
        this.campo_Total_Orden.setText( "" );
        this.caja_Observaciones_Maquila.setText("");
        this.combo_Estado_Orden.setSelectedItem( "Seleccionar.........." );
    }*/
 /*   
    public void limpiar_Tabla(){
        DefaultTableModel modelo_Tabla_Cotizacion = ( DefaultTableModel ) this.tabla_Productos_Maquila.getModel();
        modelo_Tabla_Cotizacion.setRowCount( 0 );
    }*/
 /*   
    public void botones( boolean bandera1, boolean bandera2, boolean bandera3, boolean bandera4, boolean bandera5, boolean bandera6  ){
        this.boton_Guardar_Orden.setEnabled(bandera1);
        this.boton_Agregar_Maquila.setEnabled(bandera1);
        this.boton_Nueva_Orden.setEnabled(bandera2);
        this.boton_Modificar_Orden.setEnabled(bandera3);
        this.boton_Generar_Orden.setEnabled(bandera4);
        this.combo_Estado_Orden.setEnabled(bandera5);
        this.boton_Agregar_Fila.setEnabled(bandera6);
        this.boton_Quitar_Fila.setEnabled(bandera6);
    }*/
 /*   
    public void calculo_Valores() {
        try {
            double valor_Subtotal = 0;
            for (int i = 0; i < this.tabla_Productos_Maquila.getRowCount(); i++) {
                valor_Subtotal = valor_Subtotal + (double) this.tabla_Productos_Maquila.getValueAt(i, 3);
            }
            this.campo_Total_Orden.setText(String.valueOf(valor_Subtotal));
        } catch (Exception e) {
        }
    }*/
 /*   
    public String calendario() {
        Date fecha;
        fecha = (Date) this.calendario_Orden.getDate();
        return new SimpleDateFormat("yyyy-MM-dd").format(fecha); 
    }*/
    /*
    public void limpiar_Etiquetas() {
        this.etiqueta_Indicador_Maquila.setVisible(false);
        this.etiqueta_Indicador_RUC.setVisible(false);
        this.etiqueta_Indicador_RUC.setVisible(false);
        this.etiqueta_Indicador_Direccion.setVisible(false);
        this.etiqueta_Indicador_Telefono.setVisible(false);
        this.etiqueta_Estado.setVisible(false);
    }*/
    
    public void set_Usuario(Usuario usuario, String rol){
        this.etiqueta_Nombre_Usuario.setText(usuario.getNombre() + " " + usuario.getApellido());
        this.etiqueta_Rol.setText(rol);
    }
    
    public void desactivar_Calendarios(boolean bandera) {
        this.fecha_1.setVisible(bandera);
        this.fecha_2.setVisible(bandera);
        this.boton_Fecha.setVisible(bandera);
    }

    public boolean verificar_Campos() {
        boolean bandera = true;

        if (this.fecha_1.getDate() == null) {
            bandera = false;
        }

        if (this.fecha_2.getDate() == null) {
            bandera = false;
        }

        return bandera;
    }

    public String calendario_Inicio() {
        Date fecha = this.fecha_1.getDate();
        return new SimpleDateFormat("yyyy-MM-dd").format(fecha);
    }

    public String calendario_Final() {
        Date fecha = this.fecha_2.getDate();
        return new SimpleDateFormat("yyyy-MM-dd").format(fecha);
    }
    
     public void etiqueta_Error_Etiqueta(boolean bandera){
        this.etiqueta_Error_Fecha.setVisible(bandera);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton boton_Cerrar_Sesion;
    public javax.swing.JButton boton_Fecha;
    public javax.swing.JButton boton_Generar_Orden;
    public javax.swing.JButton boton_Modificar_Orden;
    public javax.swing.JButton boton_Nueva_Orden;
    public javax.swing.JTextField campo_Busqueda;
    public javax.swing.JComboBox<String> combo_Opciones;
    public javax.swing.JLabel etiqueta_Error_Fecha;
    public javax.swing.JLabel etiqueta_Nombre_Usuario;
    public javax.swing.JLabel etiqueta_Rol;
    public com.toedter.calendar.JDateChooser fecha_1;
    public com.toedter.calendar.JDateChooser fecha_2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    public javax.swing.JTable tabla_Consulta_Orden_Produccion;
    // End of variables declaration//GEN-END:variables
}
