/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Factura;

import Modelo.Cliente;
import Modelo.Factura;
import Modelo.Usuario;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David
 */
public class Dialogo_Factura extends javax.swing.JDialog {
    private DefaultTableModel modelo_Tabla_Factura;
    private DecimalFormat formato_Numero = new DecimalFormat("#.00", new DecimalFormatSymbols(Locale.US));

    /**
     * Creates new form Dialogo_Factura
     */
    public Dialogo_Factura(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.setResizable(false);
        calendario_Factura.setDate(new Date());
        this.etiqueta_Indicador_Cliente.setVisible(false);
        this.etiqueta_Indicador_Ciudad.setVisible(false);
        this.etiqueta_Indicador_RUC.setVisible(false);
        this.etiqueta_Indicador_Direccion.setVisible(false);
        this.etiqueta_Indicador_Telefono.setVisible(false);
        this.etiqueta_Indicador_Contacto.setVisible(false);
        this.etiqueta_Indicador_Estado.setVisible(false);
        this.boton_Agregar_Fila.setEnabled(false);
        this.boton_Quitar_Fila.setEnabled(false);
        this.etiqueta_Indicador_Calendario.setVisible(false);
        this.valor_IVA.setValue(12);
        this.valor_IVA.setEnabled(false);
        this.modelo_Tabla_Factura = (DefaultTableModel) this.tabla_Productos_Factura.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calendario_Factura = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campo_Direccion_Factura = new javax.swing.JTextField();
        campo_Telefono_Factura = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Productos_Factura = new javax.swing.JTable();
        campo_Subtotal_Factura = new javax.swing.JTextField();
        campo_IVA_Factura = new javax.swing.JTextField();
        campo_Total_Factura = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        boton_Agregar_Fila = new javax.swing.JButton();
        boton_Quitar_Fila = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        campo_RUC_Factura = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        campo_Ciudad_Factura = new javax.swing.JTextField();
        combo_Estado_Factura = new javax.swing.JComboBox<>();
        combo_Cliente_Factura = new javax.swing.JTextField();
        campo_Vendedor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        caja_Observaciones_Factura = new javax.swing.JTextField();
        cantidad_Items = new javax.swing.JTextField();
        etiqueta_Indicador_Cliente = new javax.swing.JLabel();
        etiqueta_Indicador_Direccion = new javax.swing.JLabel();
        etiqueta_Indicador_Telefono = new javax.swing.JLabel();
        etiqueta_Indicador_RUC = new javax.swing.JLabel();
        etiqueta_Indicador_Ciudad = new javax.swing.JLabel();
        etiqueta_Indicador_Contacto = new javax.swing.JLabel();
        etiqueta_Indicador_Estado = new javax.swing.JLabel();
        etiqueta_No_Factura = new javax.swing.JTextField();
        campo_Codigo = new javax.swing.JTextField();
        etiqueta_Indicador_Calendario = new javax.swing.JLabel();
        valor_IVA = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        boton_Guardar_Factura = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        boton_Agregar_Cliente = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        calendario_Factura.setBackground(new java.awt.Color(255, 255, 255));
        calendario_Factura.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        calendario_Factura.setDateFormatString("yyyy-MM-dd");
        calendario_Factura.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(calendario_Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 164, 140, 24));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Fecha:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 166, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel5.setText("Cliente:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 86, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel6.setText("Direccion:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 166, 80, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel7.setText("Telefono:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 246, -1, -1));

        campo_Direccion_Factura.setEditable(false);
        campo_Direccion_Factura.setBackground(new java.awt.Color(255, 255, 255));
        campo_Direccion_Factura.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Direccion_Factura.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Direccion_Factura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Direccion_FacturaKeyTyped(evt);
            }
        });
        getContentPane().add(campo_Direccion_Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 166, 370, 24));

        campo_Telefono_Factura.setEditable(false);
        campo_Telefono_Factura.setBackground(new java.awt.Color(255, 255, 255));
        campo_Telefono_Factura.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Telefono_Factura.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Telefono_Factura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Telefono_FacturaKeyTyped(evt);
            }
        });
        getContentPane().add(campo_Telefono_Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 246, 210, 24));

        tabla_Productos_Factura.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tabla_Productos_Factura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cant", "Codigo", "Descripcion", "V. Unitario", "V. Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_Productos_Factura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tabla_Productos_FacturaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_Productos_Factura);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 366, 1090, 240));

        campo_Subtotal_Factura.setEditable(false);
        campo_Subtotal_Factura.setBackground(new java.awt.Color(255, 255, 255));
        campo_Subtotal_Factura.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Subtotal_Factura.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(campo_Subtotal_Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 616, 130, 23));

        campo_IVA_Factura.setEditable(false);
        campo_IVA_Factura.setBackground(new java.awt.Color(255, 255, 255));
        campo_IVA_Factura.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_IVA_Factura.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(campo_IVA_Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 616, 110, 23));

        campo_Total_Factura.setEditable(false);
        campo_Total_Factura.setBackground(new java.awt.Color(255, 255, 255));
        campo_Total_Factura.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        campo_Total_Factura.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(campo_Total_Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 616, 110, 23));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel10.setText("Subtotal:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 616, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel11.setText("IVA:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 621, 40, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel12.setText("Total:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 614, -1, 30));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Tipo de pago:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 126, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("No. Factura:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 86, -1, -1));

        boton_Agregar_Fila.setBackground(new java.awt.Color(255, 255, 255));
        boton_Agregar_Fila.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Agregar_Fila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mas (1).png"))); // NOI18N
        boton_Agregar_Fila.setText("Agregar item");
        boton_Agregar_Fila.setToolTipText("Agregar");
        boton_Agregar_Fila.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Agregar_Fila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Agregar_FilaActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Agregar_Fila, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 316, 120, 36));

        boton_Quitar_Fila.setBackground(new java.awt.Color(255, 255, 255));
        boton_Quitar_Fila.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Quitar_Fila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menos.png"))); // NOI18N
        boton_Quitar_Fila.setText("Borrar item");
        boton_Quitar_Fila.setToolTipText("Quitar");
        boton_Quitar_Fila.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Quitar_Fila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Quitar_FilaActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Quitar_Fila, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 316, 120, 36));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel16.setText("RUC:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 126, -1, -1));

        campo_RUC_Factura.setEditable(false);
        campo_RUC_Factura.setBackground(new java.awt.Color(255, 255, 255));
        campo_RUC_Factura.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_RUC_Factura.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_RUC_Factura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_RUC_FacturaKeyTyped(evt);
            }
        });
        getContentPane().add(campo_RUC_Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 125, 200, 24));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel18.setText("Ciudad:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 246, -1, -1));

        campo_Ciudad_Factura.setEditable(false);
        campo_Ciudad_Factura.setBackground(new java.awt.Color(255, 255, 255));
        campo_Ciudad_Factura.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Ciudad_Factura.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Ciudad_Factura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Ciudad_FacturaKeyTyped(evt);
            }
        });
        getContentPane().add(campo_Ciudad_Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 244, 200, 24));

        combo_Estado_Factura.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combo_Estado_Factura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione.........", "Credito", "Pagado", "Anular" }));
        combo_Estado_Factura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(combo_Estado_Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 121, 170, 26));

        combo_Cliente_Factura.setEditable(false);
        combo_Cliente_Factura.setBackground(new java.awt.Color(255, 255, 255));
        combo_Cliente_Factura.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combo_Cliente_Factura.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        combo_Cliente_Factura.setMaximumSize(new java.awt.Dimension(2, 25));
        combo_Cliente_Factura.setMinimumSize(new java.awt.Dimension(2, 25));
        combo_Cliente_Factura.setPreferredSize(new java.awt.Dimension(2, 25));
        getContentPane().add(combo_Cliente_Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 86, 240, 24));

        campo_Vendedor.setEditable(false);
        campo_Vendedor.setBackground(new java.awt.Color(255, 255, 255));
        campo_Vendedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Vendedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Vendedor.setMaximumSize(new java.awt.Dimension(2, 20));
        campo_Vendedor.setMinimumSize(new java.awt.Dimension(2, 20));
        campo_Vendedor.setPreferredSize(new java.awt.Dimension(2, 20));
        getContentPane().add(campo_Vendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 206, 250, 24));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel8.setText("Vendedor:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 206, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel4.setText("Observaciones:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 206, -1, -1));

        caja_Observaciones_Factura.setBackground(new java.awt.Color(255, 255, 255));
        caja_Observaciones_Factura.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        caja_Observaciones_Factura.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(caja_Observaciones_Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 204, 270, 24));

        cantidad_Items.setEditable(false);
        cantidad_Items.setBackground(new java.awt.Color(255, 255, 255));
        cantidad_Items.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cantidad_Items.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(cantidad_Items, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 616, 120, 22));

        etiqueta_Indicador_Cliente.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Cliente.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Cliente.setText("*");
        getContentPane().add(etiqueta_Indicador_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 86, -1, -1));

        etiqueta_Indicador_Direccion.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Direccion.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Direccion.setText("*");
        getContentPane().add(etiqueta_Indicador_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 166, -1, -1));

        etiqueta_Indicador_Telefono.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Telefono.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Telefono.setText("*");
        getContentPane().add(etiqueta_Indicador_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 246, -1, -1));

        etiqueta_Indicador_RUC.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_RUC.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_RUC.setText("*");
        getContentPane().add(etiqueta_Indicador_RUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 126, -1, -1));

        etiqueta_Indicador_Ciudad.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Ciudad.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Ciudad.setText("*");
        getContentPane().add(etiqueta_Indicador_Ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 246, -1, -1));

        etiqueta_Indicador_Contacto.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Contacto.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Contacto.setText("*");
        getContentPane().add(etiqueta_Indicador_Contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 206, -1, -1));

        etiqueta_Indicador_Estado.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Estado.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Estado.setText("*");
        getContentPane().add(etiqueta_Indicador_Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 126, -1, -1));

        etiqueta_No_Factura.setEditable(false);
        etiqueta_No_Factura.setBackground(new java.awt.Color(255, 255, 255));
        etiqueta_No_Factura.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        etiqueta_No_Factura.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(etiqueta_No_Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 82, 170, 24));

        campo_Codigo.setEditable(false);
        campo_Codigo.setBackground(new java.awt.Color(255, 255, 255));
        campo_Codigo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Codigo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(campo_Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 86, 110, 24));

        etiqueta_Indicador_Calendario.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Calendario.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Calendario.setText("*");
        getContentPane().add(etiqueta_Indicador_Calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 166, -1, -1));

        valor_IVA.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        valor_IVA.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        valor_IVA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                valor_IVAStateChanged(evt);
            }
        });
        valor_IVA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valor_IVAKeyTyped(evt);
            }
        });
        getContentPane().add(valor_IVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 646, 110, 23));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel9.setText("%:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 646, -1, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos del cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, 640, 240));

        jLabel21.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 296, 1150, 390));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/supermercado.png"))); // NOI18N
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 606, 50, 40));

        jLabel20.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 46, 460, 240));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);

        boton_Guardar_Factura.setBackground(new java.awt.Color(255, 255, 255));
        boton_Guardar_Factura.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Guardar_Factura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disquete.png"))); // NOI18N
        boton_Guardar_Factura.setText("Guardar");
        boton_Guardar_Factura.setToolTipText("Agregar cotizacion");
        boton_Guardar_Factura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Guardar_Factura.setFocusable(false);
        boton_Guardar_Factura.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Guardar_Factura.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Guardar_Factura.setMinimumSize(new java.awt.Dimension(100, 37));
        boton_Guardar_Factura.setPreferredSize(new java.awt.Dimension(100, 37));
        jToolBar1.add(boton_Guardar_Factura);
        jToolBar1.add(jSeparator1);

        boton_Agregar_Cliente.setBackground(new java.awt.Color(255, 255, 255));
        boton_Agregar_Cliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Agregar_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario-especialista.png"))); // NOI18N
        boton_Agregar_Cliente.setText("Cliente");
        boton_Agregar_Cliente.setToolTipText("Agregar cliente");
        boton_Agregar_Cliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Agregar_Cliente.setMaximumSize(new java.awt.Dimension(100, 40));
        boton_Agregar_Cliente.setMinimumSize(new java.awt.Dimension(100, 40));
        boton_Agregar_Cliente.setPreferredSize(new java.awt.Dimension(80, 40));
        jToolBar1.add(boton_Agregar_Cliente);
        jToolBar1.add(jSeparator2);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calculadora.png"))); // NOI18N
        jButton1.setText("Calculadora");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setMaximumSize(new java.awt.Dimension(111, 37));
        jButton1.setMinimumSize(new java.awt.Dimension(111, 37));
        jButton1.setPreferredSize(new java.awt.Dimension(111, 37));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1173, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campo_Direccion_FacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Direccion_FacturaKeyTyped
        char c = evt.getKeyChar();
        if( c == evt.VK_SPACE && this.campo_Direccion_Factura.getText().length() == 0 ) evt.consume();
        else if(  ( c < 'a' || c > 'z' ) && ( c < 'A' || c>'Z' ) && ( c < '0' || c > '9' ) && ( c < '-' || c > '.' ) && c != evt.VK_SPACE ){
            evt.consume();
        }
    }//GEN-LAST:event_campo_Direccion_FacturaKeyTyped

    private void campo_Telefono_FacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Telefono_FacturaKeyTyped
        char c = evt.getKeyChar();
        if( c < '0'  || c > '9' || this.campo_Telefono_Factura.getText().length() >= 9 ) evt.consume();
    }//GEN-LAST:event_campo_Telefono_FacturaKeyTyped

    private void tabla_Productos_FacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_Productos_FacturaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tabla_Productos_FacturaKeyTyped

    private void boton_Agregar_FilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Agregar_FilaActionPerformed
        this.cantidad_Items.setText(String.valueOf(this.tabla_Productos_Factura.getRowCount()));
    }//GEN-LAST:event_boton_Agregar_FilaActionPerformed

    private void boton_Quitar_FilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Quitar_FilaActionPerformed
        DefaultTableModel modelo_Tabla_Maquila = (DefaultTableModel) this.tabla_Productos_Factura.getModel();

        try {
            modelo_Tabla_Maquila.removeRow(this.tabla_Productos_Factura.getSelectedRow());
            this.cantidad_Items.setText(String.valueOf(this.tabla_Productos_Factura.getRowCount()));
            this.calculo_Valores();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_boton_Quitar_FilaActionPerformed

    private void campo_RUC_FacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_RUC_FacturaKeyTyped
        char c = evt.getKeyChar();
        if( c < '0'  || c > '9' || this.campo_RUC_Factura.getText().length() >= 13 ) evt.consume();
    }//GEN-LAST:event_campo_RUC_FacturaKeyTyped

    private void campo_Ciudad_FacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Ciudad_FacturaKeyTyped
        char c = evt.getKeyChar();
        if( c == evt.VK_SPACE && this.campo_Ciudad_Factura.getText().length() == 0 ) evt.consume();
        else if(  ( c < 'a' || c > 'z' ) && ( c < 'A' || c>'Z' ) && c != evt.VK_SPACE ){
            evt.consume();
        }
    }//GEN-LAST:event_campo_Ciudad_FacturaKeyTyped

    private void valor_IVAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_valor_IVAStateChanged

        if ((Integer) this.valor_IVA.getValue() < 1) {
            this.valor_IVA.setValue(1);
        } else if ((Integer) this.valor_IVA.getValue() > 25) {
            this.valor_IVA.setValue(25);
        } else {
            calculo_Valores();
        }
    }//GEN-LAST:event_valor_IVAStateChanged

    private void valor_IVAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valor_IVAKeyTyped

    }//GEN-LAST:event_valor_IVAKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Runtime rt = Runtime.getRuntime();
            Process p = rt.exec("calc");
            p.waitFor();
        } catch (IOException ioe) {
            ioe.printStackTrace();
        } catch (InterruptedException ie) {
            ie.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean etiquetas( ){
        boolean bandera = true;
        
        if( this.combo_Cliente_Factura.getText().isEmpty() ){
            this.etiqueta_Indicador_Cliente.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Cliente.setVisible( false );
        }
        
        if (this.calendario_Factura.getDate() == null) {
            this.etiqueta_Indicador_Calendario.setVisible(bandera);
            bandera = false;
        }else{
            this.etiqueta_Indicador_Calendario.setVisible(false);
        }
        
        if( this.campo_Ciudad_Factura.getText().isEmpty() ){
            this.etiqueta_Indicador_Ciudad.setVisible( true );
            bandera = false;
        }else{ 
           this.etiqueta_Indicador_Ciudad.setVisible( false );
        }
            
        if( this.campo_RUC_Factura.getText().matches( "[0-9][0-9]{12}" ) ){
            this.etiqueta_Indicador_RUC.setVisible( false );
        }else if(this.campo_RUC_Factura.getText().matches( "[0-9][0-9]{9}" ) ){
            this.etiqueta_Indicador_RUC.setVisible( false );
        }
        else{
            this.etiqueta_Indicador_RUC.setVisible( true );
            bandera = false;
        }
            
        if( this.campo_Direccion_Factura.getText().isEmpty() ){ 
            this.etiqueta_Indicador_Direccion.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Direccion.setVisible( false );
        }
            
        if( this.campo_Telefono_Factura.getText().matches( "[0][1-9][0-9]{7}" ) ){
            this.etiqueta_Indicador_Telefono.setVisible( false );
        }else{
            this.etiqueta_Indicador_Telefono.setVisible( true );
            bandera = false;
        }  
            
        if( this.campo_Vendedor.getText().isEmpty() ){
            this.etiqueta_Indicador_Contacto.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Contacto.setVisible( false );
        }
        
        if( this.combo_Estado_Factura.getSelectedItem().equals( "Seleccione........." ) ){
           this.etiqueta_Indicador_Estado.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Estado.setVisible( false );
        }
        return bandera;
    }
    
    public String[] evaluar_Tabla() {
        DefaultTableModel modelo_Tabla_Factura = (DefaultTableModel) this.tabla_Productos_Factura.getModel();
        String[] valores = new String[6];

        for (int i = 0; i < modelo_Tabla_Factura.getRowCount(); i++) {
            valores[0] = modelo_Tabla_Factura.getValueAt(i, 0) + ";" + valores[0];
            valores[1] = modelo_Tabla_Factura.getValueAt(i, 1) + ";" + valores[1];
            valores[2] = modelo_Tabla_Factura.getValueAt(i, 2) + ";" + valores[2];
            valores[3] = modelo_Tabla_Factura.getValueAt(i, 3) + ";" + valores[3];
            valores[4] = modelo_Tabla_Factura.getValueAt(i, 4) + ";" + valores[4];
        }
        return valores;
    }
    
    public void valores_Clientes(Cliente cliente, Usuario usuario) {
        this.campo_Codigo.setText(cliente.getCodigo_Cliente());
        this.combo_Cliente_Factura.setText(cliente.getCliente());
        this.campo_RUC_Factura.setText(cliente.getRUC());
        this.campo_Direccion_Factura.setText(cliente.getDireccion());
        this.campo_Ciudad_Factura.setText(cliente.getCiudad());
        this.campo_Telefono_Factura.setText(cliente.getTelefono());
        this.campo_Vendedor.setText(usuario.getNombre() + " " + usuario.getApellido());
    }

    public String calendario() {
        Date fecha;
        fecha = (Date) this.calendario_Factura.getDate();
        return new SimpleDateFormat("yyyy-MM-dd").format(fecha);
    }

    public void calculo_Valores() {
        try {
            double valor_Subtotal = 0;
            for (int i = 0; i < this.modelo_Tabla_Factura.getRowCount(); i++) {
                valor_Subtotal = valor_Subtotal + (double) this.modelo_Tabla_Factura.getValueAt(i, 4);
            }
            this.campo_Subtotal_Factura.setText(this.formato_Numero.format(valor_Subtotal));
            this.campo_IVA_Factura.setText(this.formato_Numero.format(valor_Subtotal * (Integer) this.valor_IVA.getValue() / 100));
            this.campo_Total_Factura.setText(this.formato_Numero.format(Double.valueOf(this.campo_IVA_Factura.getText()) + valor_Subtotal));
        } catch (Exception e) {
        }
    }

    public void valores_Clientes(String codigo, String cliente, String direccion, String telefono, String RUC, String ciudad, String nombre, String apellido, String c) {
        this.campo_Codigo.setText(codigo);
        this.combo_Cliente_Factura.setText(cliente);
        this.campo_RUC_Factura.setText(RUC);
        this.campo_Direccion_Factura.setText(direccion);
        this.campo_Ciudad_Factura.setText(ciudad);
        this.campo_Telefono_Factura.setText(telefono);
        this.campo_Vendedor.setText(nombre + " " + apellido);
    }
    
    public void valores_Tabla_Factura(ArrayList<Factura> lista_Factura) {
        DefaultTableModel modelo_Tabla_Factura = (DefaultTableModel) this.tabla_Productos_Factura.getModel();
        modelo_Tabla_Factura.setRowCount(0);

        String[] cantidad = lista_Factura.get(0).getCantidad().split(";");
        String[] codigo = lista_Factura.get(0).getCodigo().split(";");
        String[] descripcion = lista_Factura.get(0).getDescripcion().split(";");
        String[] v_Unitario = lista_Factura.get(0).getV_Unitario().split(";");
        String[] v_Total = lista_Factura.get(0).getV_Total().split(";");

        for (int i = 0; i < codigo.length - 1; i++) {
            Object[] valores_Tabla = {cantidad[i], codigo[i], descripcion[i], Double.parseDouble(v_Unitario[i]), Double.parseDouble(v_Total[i])};
            modelo_Tabla_Factura.addRow(valores_Tabla);
        }
        this.cantidad_Items.setText(String.valueOf(codigo.length - 1));
        this.valores_Factura(lista_Factura.get(0));
    }

    public void valores_Factura(Factura factura) {
        this.combo_Estado_Factura.setSelectedItem(factura.getEstado());
        this.campo_Subtotal_Factura.setText(String.valueOf(factura.getV_Subtotal()));
        this.campo_IVA_Factura.setText(String.valueOf(factura.getIVA()));
        this.campo_Total_Factura.setText(String.valueOf(factura.getValor_Total()));
        this.etiqueta_No_Factura.setText(factura.getNo_Factura());
        this.campo_Vendedor.setText(factura.getVendedor());
        this.caja_Observaciones_Factura.setText(factura.getObservaciones());
        this.valor_IVA.setValue((int) ((factura.getIVA() / factura.getV_Subtotal()) * 100));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dialogo_Factura dialog = new Dialogo_Factura(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton boton_Agregar_Cliente;
    public javax.swing.JButton boton_Agregar_Fila;
    public javax.swing.JButton boton_Guardar_Factura;
    public javax.swing.JButton boton_Quitar_Fila;
    public javax.swing.JTextField caja_Observaciones_Factura;
    public com.toedter.calendar.JDateChooser calendario_Factura;
    public javax.swing.JTextField campo_Ciudad_Factura;
    public javax.swing.JTextField campo_Codigo;
    public javax.swing.JTextField campo_Direccion_Factura;
    public javax.swing.JTextField campo_IVA_Factura;
    public javax.swing.JTextField campo_RUC_Factura;
    public javax.swing.JTextField campo_Subtotal_Factura;
    public javax.swing.JTextField campo_Telefono_Factura;
    public javax.swing.JTextField campo_Total_Factura;
    public javax.swing.JTextField campo_Vendedor;
    private javax.swing.JTextField cantidad_Items;
    public javax.swing.JTextField combo_Cliente_Factura;
    public javax.swing.JComboBox<String> combo_Estado_Factura;
    private javax.swing.JLabel etiqueta_Indicador_Calendario;
    private javax.swing.JLabel etiqueta_Indicador_Ciudad;
    private javax.swing.JLabel etiqueta_Indicador_Cliente;
    private javax.swing.JLabel etiqueta_Indicador_Contacto;
    private javax.swing.JLabel etiqueta_Indicador_Direccion;
    private javax.swing.JLabel etiqueta_Indicador_Estado;
    private javax.swing.JLabel etiqueta_Indicador_RUC;
    private javax.swing.JLabel etiqueta_Indicador_Telefono;
    public javax.swing.JTextField etiqueta_No_Factura;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    public javax.swing.JTable tabla_Productos_Factura;
    public javax.swing.JSpinner valor_IVA;
    // End of variables declaration//GEN-END:variables
}
