/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Factura;

import Modelo.Factura;
import Modelo.Usuario;
import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author David
 */
public class Panel_Factura extends javax.swing.JPanel {
    private DefaultTableModel       modelo_Tabla_Factura;
    private DecimalFormat           formato_Numero = new DecimalFormat("#.00", new DecimalFormatSymbols(Locale.US));
    /**
     * Creates new form Panel_Cotizacion
     */
    public Panel_Factura() {
        initComponents();
        //calendario_Factura.setDate( new Date() );
       // this.modelo_Tabla_Factura = ( DefaultTableModel )  this.tabla_Productos_Factura.getModel();
       // this.tabla_Productos_Factura.getTableHeader().setFont( new Font( "Arial", Font.BOLD, 14 ) );
       // this.tabla_Productos_Factura.getTableHeader().setBackground( new Color( 32, 136, 203 ) );
       // this.tabla_Productos_Factura.getTableHeader().setForeground( new Color( 255, 255, 255) ); 
        this.boton_Modificar_Factura.setEnabled( false );
        this.boton_Imprimir_Facturacion.setEnabled(false);
        //this.etiqueta_Indicador_Cliente.setVisible( false );
        //this.etiqueta_Indicador_Ciudad.setVisible( false );
        //this.etiqueta_Indicador_RUC.setVisible( false );
        //this.etiqueta_Indicador_Direccion.setVisible( false );
       // this.etiqueta_Indicador_Telefono.setVisible( false );
       // this.etiqueta_Indicador_Contacto.setVisible( false );
       // this.etiqueta_Indicador_Estado.setVisible( false );
        this.boton_Modificar_Factura.setEnabled( false );
        this.fecha_1.setVisible(false);
        this.fecha_2.setVisible(false);
        this.boton_Fecha.setVisible(false);
        this.fecha_1.setDate( new Date() );
        this.fecha_2.setDate( new Date() );
        this.etiqueta_Error_Fecha.setVisible(false);
       // this.boton_Agregar_Fila.setEnabled( false );
      //  this.boton_Quitar_Fila.setEnabled( false );
       // this.etiqueta_Indicador_Calendario.setVisible(false);
       this.tabla_Consulta_Factura.getTableHeader().setReorderingAllowed(false) ;
      //  this.valor_IVA.setValue(12);
       // this.valor_IVA.setEnabled(false);
    }
    
    public void Roles(String rol) {
        if (rol.equals("Vendedor")) {
            boolean[] bandera = {true, true, true, true, true, true, true};
            this.habilitar_Rol(bandera);
        }

        if (rol.equals("Bodeguero")) {
            boolean[] bandera = {false, false, false, false, false, false, false};
            this.habilitar_Rol(bandera);
        }

        if (rol.equals("Contador")) {
            boolean[] bandera = {true, false, false, true, false, false, false};
            this.habilitar_Rol(bandera);
        }

        if (rol.equals("Administrador")) {
            boolean[] bandera = {true, false, false, true, false, false, false};
            this.habilitar_Rol(bandera);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        boton_Nueva_Factura = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        boton_Modificar_Factura = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        boton_Imprimir_Facturacion = new javax.swing.JButton();
        boton_Cerrar_Sesion = new javax.swing.JButton();
        etiqueta_Rol = new javax.swing.JLabel();
        etiqueta_Nombre_Usuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        campo_Busqueda = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        fecha_1 = new com.toedter.calendar.JDateChooser();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        fecha_2 = new com.toedter.calendar.JDateChooser();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        etiqueta_Error_Fecha = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        boton_Fecha = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        combo_Opciones = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Consulta_Factura = new javax.swing.JTable();

        setBackground(new java.awt.Color(229, 229, 229));
        setMaximumSize(new java.awt.Dimension(1400, 800));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setPreferredSize(new java.awt.Dimension(1390, 790));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator1);

        boton_Nueva_Factura.setBackground(new java.awt.Color(255, 255, 255));
        boton_Nueva_Factura.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Nueva_Factura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-archivo.png"))); // NOI18N
        boton_Nueva_Factura.setText("Nuevo");
        boton_Nueva_Factura.setToolTipText("Nueva cotizacion");
        boton_Nueva_Factura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Nueva_Factura.setFocusable(false);
        boton_Nueva_Factura.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Nueva_Factura.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Nueva_Factura.setMinimumSize(new java.awt.Dimension(100, 37));
        boton_Nueva_Factura.setPreferredSize(new java.awt.Dimension(100, 37));
        boton_Nueva_Factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Nueva_FacturaActionPerformed(evt);
            }
        });
        jToolBar1.add(boton_Nueva_Factura);
        jToolBar1.add(jSeparator3);

        boton_Modificar_Factura.setBackground(new java.awt.Color(255, 255, 255));
        boton_Modificar_Factura.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Modificar_Factura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar-documento.png"))); // NOI18N
        boton_Modificar_Factura.setText("Modificar");
        boton_Modificar_Factura.setToolTipText("Modificar cotizacion");
        boton_Modificar_Factura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Modificar_Factura.setFocusable(false);
        boton_Modificar_Factura.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Modificar_Factura.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Modificar_Factura.setMinimumSize(new java.awt.Dimension(100, 37));
        boton_Modificar_Factura.setPreferredSize(new java.awt.Dimension(100, 37));
        boton_Modificar_Factura.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(boton_Modificar_Factura);
        jToolBar1.add(jSeparator2);
        jToolBar1.add(jSeparator4);

        boton_Imprimir_Facturacion.setBackground(new java.awt.Color(255, 255, 255));
        boton_Imprimir_Facturacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Imprimir_Facturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportar 1.png"))); // NOI18N
        boton_Imprimir_Facturacion.setText("Factura");
        boton_Imprimir_Facturacion.setToolTipText("Generar factura");
        boton_Imprimir_Facturacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Imprimir_Facturacion.setFocusable(false);
        boton_Imprimir_Facturacion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Imprimir_Facturacion.setMaximumSize(new java.awt.Dimension(100, 40));
        boton_Imprimir_Facturacion.setMinimumSize(new java.awt.Dimension(100, 40));
        boton_Imprimir_Facturacion.setPreferredSize(new java.awt.Dimension(100, 40));
        jToolBar1.add(boton_Imprimir_Facturacion);

        add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 790));

        boton_Cerrar_Sesion.setBackground(new java.awt.Color(255, 255, 255));
        boton_Cerrar_Sesion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Cerrar_Sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exit-32.png"))); // NOI18N
        boton_Cerrar_Sesion.setText("Cerrar");
        boton_Cerrar_Sesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(boton_Cerrar_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 120, 40));

        etiqueta_Rol.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        etiqueta_Rol.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(etiqueta_Rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(1134, 20, 147, 20));

        etiqueta_Nombre_Usuario.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        etiqueta_Nombre_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        etiqueta_Nombre_Usuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        etiqueta_Nombre_Usuario.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(etiqueta_Nombre_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 180, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo blanco.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 180, 40));

        jToolBar2.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar2.setRollover(true);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        jLabel1.setText("     ");
        jToolBar2.add(jLabel1);

        campo_Busqueda.setEditable(false);
        campo_Busqueda.setBackground(new java.awt.Color(255, 255, 255));
        campo_Busqueda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Busqueda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campo_Busqueda.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        campo_Busqueda.setMaximumSize(new java.awt.Dimension(450, 30));
        campo_Busqueda.setMinimumSize(new java.awt.Dimension(450, 30));
        campo_Busqueda.setPreferredSize(new java.awt.Dimension(450, 30));
        jToolBar2.add(campo_Busqueda);
        jToolBar2.add(jSeparator5);

        fecha_1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Desde", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        fecha_1.setDateFormatString("yyyy-MM-dd");
        jToolBar2.add(fecha_1);
        jToolBar2.add(jSeparator6);

        fecha_2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hasta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        fecha_2.setDateFormatString("yyyy-MM-dd");
        jToolBar2.add(fecha_2);
        jToolBar2.add(jSeparator9);

        etiqueta_Error_Fecha.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etiqueta_Error_Fecha.setForeground(new java.awt.Color(204, 0, 51));
        etiqueta_Error_Fecha.setText("*");
        jToolBar2.add(etiqueta_Error_Fecha);
        jToolBar2.add(jSeparator7);

        boton_Fecha.setBackground(new java.awt.Color(255, 255, 255));
        boton_Fecha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Fecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/busqueda (1).png"))); // NOI18N
        boton_Fecha.setText("Buscar");
        boton_Fecha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Fecha.setMaximumSize(new java.awt.Dimension(75, 40));
        boton_Fecha.setMinimumSize(new java.awt.Dimension(75, 40));
        boton_Fecha.setPreferredSize(new java.awt.Dimension(75, 40));
        jToolBar2.add(boton_Fecha);
        jToolBar2.add(jSeparator8);

        combo_Opciones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combo_Opciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar.....", "Por numero", "Por nombre", "Por RUC", "Por fecha" }));
        combo_Opciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar2.add(combo_Opciones);

        add(jToolBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 990, 40));

        tabla_Consulta_Factura.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tabla_Consulta_Factura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No_Factura", "Cliente", "RUC/ CI", "Estado", "Valor", "Fecha", "Id_Vendedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_Consulta_Factura);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 1290, 750));
    }// </editor-fold>//GEN-END:initComponents

    private void boton_Nueva_FacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Nueva_FacturaActionPerformed

    }//GEN-LAST:event_boton_Nueva_FacturaActionPerformed
/*
    public void valores_Clientes( String codigo, String cliente, String direccion, String telefono, String RUC, String ciudad, String nombre, String apellido ){
        this.campo_Codigo.setText(codigo);
        this.combo_Cliente_Factura.setText(cliente);
        this.campo_RUC_Factura.setText( RUC );
        this.campo_Direccion_Factura.setText( direccion );
        this.campo_Ciudad_Factura.setText( ciudad );
        this.campo_Telefono_Factura.setText( telefono );
        this.campo_Vendedor.setText(nombre + " " + apellido);
    }
    
    public void valores_Factura( String estado, double subtotal, double IVA, double valor_Total, String no_Factura, String vendedor, String observaciones ){
        this.combo_Estado_Factura.setSelectedItem( estado );
        this.campo_Subtotal_Factura.setText( String.valueOf( subtotal ) );
        this.campo_IVA_Factura.setText( String.valueOf( IVA ) );
        this.campo_Total_Factura.setText( String.valueOf( valor_Total ) );
        this.etiqueta_No_Factura.setText( no_Factura  );
        this.campo_Vendedor.setText(vendedor);
        this.caja_Observaciones_Factura.setText(observaciones);
        this.valor_IVA.setValue((int)((IVA/subtotal)*100));
    }
    
    public void valores_Tabla_Factura(ArrayList<Factura>  lista_Factura){
        DefaultTableModel modelo_Tabla_Factura = ( DefaultTableModel )  this.tabla_Productos_Factura.getModel();
        modelo_Tabla_Factura.setRowCount(0);
        
        String[] cantidad = lista_Factura.get(0).getCantidad().split(";");
        String[] codigo = lista_Factura.get(0).getCodigo().split(";");
        String[] descripcion = lista_Factura.get(0).getDescripcion().split(";");
        String[] v_Unitario = lista_Factura.get(0).getV_Unitario().split(";");
        String[] v_Total = lista_Factura.get(0).getV_Total().split(";");

        for (int i = 0; i < codigo.length - 1; i++) {
            Object[] valores_Tabla = {cantidad[i], codigo[i], descripcion[i], Double.parseDouble(v_Unitario[i]), Double.parseDouble(v_Total[i])};
            modelo_Tabla_Factura.addRow(valores_Tabla);
        }
        this.cantidad_Items.setText(String.valueOf(codigo.length-1));
        this.valores_Factura(lista_Factura.get(0).getEstado(), lista_Factura.get(0).getV_Subtotal(), lista_Factura.get(0).getIVA(), lista_Factura.get(0).getValor_Total(), lista_Factura.get(0).getNo_Factura(), lista_Factura.get(0).getVendedor(), lista_Factura.get(0).getObservaciones());  
    }
    
    public boolean etiquetas( ){
        boolean bandera = true;
        
        if( this.combo_Cliente_Factura.getText().isEmpty() ){
            this.etiqueta_Indicador_Cliente.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Cliente.setVisible( false );
        }
        
        if (this.calendario_Factura.getDate() == null) {
            this.etiqueta_Indicador_Calendario.setVisible(bandera);
            bandera = false;
        }else{
            this.etiqueta_Indicador_Calendario.setVisible(false);
        }
        
        if( this.campo_Ciudad_Factura.getText().isEmpty() ){
            this.etiqueta_Indicador_Ciudad.setVisible( true );
            bandera = false;
        }else{ 
           this.etiqueta_Indicador_Ciudad.setVisible( false );
        }
            
        if( this.campo_RUC_Factura.getText().matches( "[0-9][0-9]{12}" ) ){
            this.etiqueta_Indicador_RUC.setVisible( false );
        }else if(this.campo_RUC_Factura.getText().matches( "[0-9][0-9]{9}" ) ){
            this.etiqueta_Indicador_RUC.setVisible( false );
        }
        else{
            this.etiqueta_Indicador_RUC.setVisible( true );
            bandera = false;
        }
            
        if( this.campo_Direccion_Factura.getText().isEmpty() ){ 
            this.etiqueta_Indicador_Direccion.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Direccion.setVisible( false );
        }
            
        if( this.campo_Telefono_Factura.getText().matches( "[0][1-9][0-9]{7}" ) ){
            this.etiqueta_Indicador_Telefono.setVisible( false );
        }else{
            this.etiqueta_Indicador_Telefono.setVisible( true );
            bandera = false;
        }  
            
        if( this.campo_Vendedor.getText().isEmpty() ){
            this.etiqueta_Indicador_Contacto.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Contacto.setVisible( false );
        }
        
        if( this.combo_Estado_Factura.getSelectedItem().equals( "Seleccione........." ) ){
           this.etiqueta_Indicador_Estado.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Estado.setVisible( false );
        }
        return bandera;
    }
    
    public String[] evaluar_Tabla() {
        DefaultTableModel modelo_Tabla_Factura = (DefaultTableModel) this.tabla_Productos_Factura.getModel();
        String[] valores = new String[6];

        for (int i = 0; i < modelo_Tabla_Factura.getRowCount(); i++) {
            valores[0] = modelo_Tabla_Factura.getValueAt(i, 0) + ";" + valores[0];
            valores[1] = modelo_Tabla_Factura.getValueAt(i, 1) + ";" + valores[1];
            valores[2] = modelo_Tabla_Factura.getValueAt(i, 2) + ";" + valores[2];
            valores[3] = modelo_Tabla_Factura.getValueAt(i, 3) + ";" + valores[3];
            valores[4] = modelo_Tabla_Factura.getValueAt(i, 4) + ";" + valores[4];
        }
        return valores;
    }
    
    public void limpiar_Valores() {
        this.combo_Cliente_Factura.setText("");
        this.campo_Subtotal_Factura.setText("");
        this.campo_IVA_Factura.setText("");
        this.campo_Total_Factura.setText("");
        this.combo_Cliente_Factura.setText("");
        this.combo_Estado_Factura.setSelectedItem("Seleccione.........");
        this.caja_Observaciones_Factura.setText("");
        this.cantidad_Items.setText("");
        this.valor_IVA.setValue(12);
    }
    
    public void limpiar_Tabla(){
        DefaultTableModel modelo_Tabla_Cotizacion = ( DefaultTableModel ) this.tabla_Productos_Factura.getModel();
        modelo_Tabla_Cotizacion.setRowCount( 0 );
    }
    
    public void botones(boolean bandera1, boolean bandera2, boolean bandera3, boolean bandera4, boolean bandera5) {
        this.boton_Guardar_Factura.setEnabled(bandera1);
        this.boton_Agregar_Cliente.setEnabled(bandera1);
        this.boton_Nueva_Factura.setEnabled(bandera2);
        this.boton_Imprimir_Facturacion.setEnabled(!bandera1);
        this.boton_Modificar_Factura.setEnabled(bandera3);
        this.combo_Estado_Factura.setEnabled(bandera4);
        this.boton_Agregar_Fila.setEnabled(bandera5);
        this.boton_Quitar_Fila.setEnabled(bandera5);
        this.valor_IVA.setEnabled(bandera5);
    }
    
    
    public String calendario(){
        Date fecha;
        fecha = (Date) this.calendario_Factura.getDate();
        return  new SimpleDateFormat("yyyy-MM-dd").format( fecha ) ;
    }

    public void calculo_Valores() {
        try {
            double valor_Subtotal = 0;
            for (int i = 0; i < this.modelo_Tabla_Factura.getRowCount(); i++) {
                valor_Subtotal = valor_Subtotal + (double) this.modelo_Tabla_Factura.getValueAt(i, 4);
            }
            this.campo_Subtotal_Factura.setText(this.formato_Numero.format(valor_Subtotal));
            this.campo_IVA_Factura.setText(this.formato_Numero.format(valor_Subtotal * (Integer)this.valor_IVA.getValue()/100));
            this.campo_Total_Factura.setText(this.formato_Numero.format(Double.valueOf(this.campo_IVA_Factura.getText()) + valor_Subtotal));
        } catch (Exception e) {
        }
    }
    
    public void limpiar_Etiquetas() {
        this.etiqueta_Indicador_Cliente.setVisible(false);
        this.etiqueta_Indicador_Ciudad.setVisible(false);
        this.etiqueta_Indicador_RUC.setVisible(false);
        this.etiqueta_Indicador_RUC.setVisible(false);
        this.etiqueta_Indicador_Direccion.setVisible(false);
        this.etiqueta_Indicador_Telefono.setVisible(false);
        this.etiqueta_Indicador_Contacto.setVisible(false);
        this.etiqueta_Indicador_Estado.setVisible(false);
    }
   */ 
    
    public String calendario_Inicio() {
        Date fecha = this.fecha_1.getDate();
        return new SimpleDateFormat("yyyy-MM-dd").format(fecha);
    }
    
    public String calendario_Final() {   
        Date fecha = this.fecha_2.getDate();
        return new SimpleDateFormat("yyyy-MM-dd").format(fecha);
    }
    
    public boolean verificar_Campos() {
        boolean bandera = true;
        
        if (this.fecha_1.getDate() == null) {
            bandera = false;
        }

        if (this.fecha_2.getDate() == null) {
            bandera = false;
        }

        return bandera;
    }
    
    public void etiqueta_Error_Etiqueta(boolean bandera){
        this.etiqueta_Error_Fecha.setVisible(bandera);
    }
    
    public void desactivar_Calendarios(boolean bandera) {
        this.fecha_1.setVisible(bandera);
        this.fecha_2.setVisible(bandera);
        this.boton_Fecha.setVisible(bandera);
    }
    
    public void habilitar_Rol(boolean[] bandera) {
        this.boton_Nueva_Factura.setVisible(bandera[0]);
        //this.boton_Guardar_Factura.setVisible(bandera[1]);
        this.boton_Modificar_Factura.setVisible(bandera[2]);
        this.boton_Imprimir_Facturacion.setVisible(bandera[3]);
        //this.boton_Agregar_Cliente.setVisible(bandera[4]);
        //this.boton_Agregar_Fila.setVisible(bandera[5]);
        //this.boton_Quitar_Fila.setVisible(bandera[6]);
    }
    
    public void set_Usuario(Usuario usuario, String rol){
        this.etiqueta_Nombre_Usuario.setText(usuario.getNombre() + " " + usuario.getApellido());
        this.etiqueta_Rol.setText(rol);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton boton_Cerrar_Sesion;
    public javax.swing.JButton boton_Fecha;
    public javax.swing.JButton boton_Imprimir_Facturacion;
    public javax.swing.JButton boton_Modificar_Factura;
    public javax.swing.JButton boton_Nueva_Factura;
    public javax.swing.JTextField campo_Busqueda;
    public javax.swing.JComboBox<String> combo_Opciones;
    public javax.swing.JLabel etiqueta_Error_Fecha;
    public javax.swing.JLabel etiqueta_Nombre_Usuario;
    public javax.swing.JLabel etiqueta_Rol;
    public com.toedter.calendar.JDateChooser fecha_1;
    public com.toedter.calendar.JDateChooser fecha_2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    public javax.swing.JTable tabla_Consulta_Factura;
    // End of variables declaration//GEN-END:variables
}
