/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Compras;

import Modelo.Usuario;
import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David
 */
public class Panel_Compras extends javax.swing.JPanel {
    DefaultTableModel modelo_Tabla_Datos_Compras;
    /**
     * Creates new form Panel_Compra
     */
    public Panel_Compras() {
        initComponents();
       // this.grupo_Botones.add( radio_Boton_No_Ingresados );
       // this.grupo_Botones.add( radio_Boton_Ingresados );
       // this.radio_Boton_Ingresados.setEnabled(false);
       // this.radio_Boton_No_Ingresados.setEnabled(false);
        this.combo_Opcion.setEnabled(false);
        this.combo_Filtrar.setEnabled(false);/*
        this.tabla_Consulta_Orden_Compra.getTableHeader().setFont( new Font( "Arial", Font.BOLD, 13 ) );
        this.tabla_Consulta_Orden_Compra.getTableHeader().setBackground( new Color( 32, 136, 203 ) );
        this.tabla_Consulta_Orden_Compra.getTableHeader().setForeground( new Color( 255, 255, 255) );
        this.tabla_Consulta_Orden_Compra.getTableHeader().setFont( new Font( "Arial", Font.BOLD, 13 ) );
        this.tabla_Consulta_Orden_Compra.getTableHeader().setBackground( new Color( 32, 136, 203 ) );
        this.tabla_Consulta_Orden_Compra.getTableHeader().setForeground( new Color( 255, 255, 255) );*/
        this.tabla_Consulta_Orden_Compra.getTableHeader().setReorderingAllowed(false) ;
    }
    
    public boolean etiquetas( boolean bandera, int fila, JButton boton ){
        modelo_Tabla_Datos_Compras = ( DefaultTableModel )  tabla_Consulta_Orden_Compra.getModel();
        
        if( modelo_Tabla_Datos_Compras.getValueAt( fila, 6 ) == null ){
            bandera = false;
        }
        
        if( modelo_Tabla_Datos_Compras.getValueAt( fila, 7 ) == null ){
            bandera = false;
        }
        
        if( boton.getText().equals( "Subir Archivo" )){
            bandera = false;
        }
        
        if( modelo_Tabla_Datos_Compras.getValueAt( fila, 9 ) == "Seleccione..." ){
            bandera = false;
        }
        return bandera;
    }
    
    public String calendario_Fecha( int fila ){
        Date fecha =  (Date) tabla_Consulta_Orden_Compra.getValueAt( fila, 7);
        return  new SimpleDateFormat("yyyy-MM-dd").format( fecha ) ;
    }
    
    public void valores_Proveedor(String proveedor, String RUC, String direccion, String correo, String telefono){
        this.campo_Proveedor.setText(proveedor);
        this.campo_RUC.setText(RUC);
        this.campo_Direccion.setText(direccion);
        this.campo_Correo.setText(correo);
        this.campo_Telefono.setText(telefono);
    }
    
    public void limpiar_Campos(){
        this.campo_Proveedor.setText("");
        this.campo_RUC.setText("");
        this.campo_Direccion.setText("");
        this.campo_Correo.setText("");
        this.campo_Telefono.setText("");
    }
    
    public void set_Usuario(Usuario usuario, String rol){
        this.etiqueta_Nombre_Usuario.setText(usuario.getNombre() + " " + usuario.getApellido());
        this.etiqueta_Rol.setText(rol);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_Botones = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_Consulta_Orden_Compra = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        boton_Buscar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campo_Proveedor = new javax.swing.JTextField();
        campo_RUC = new javax.swing.JTextField();
        campo_Direccion = new javax.swing.JTextField();
        boton_Cerrar_Sesion = new javax.swing.JButton();
        etiqueta_Nombre_Usuario = new javax.swing.JLabel();
        etiqueta_Rol = new javax.swing.JLabel();
        campo_Correo = new javax.swing.JTextField();
        campo_Telefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campo_Busqueda = new javax.swing.JTextField();
        combo_Filtrar = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        combo_Opcion = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(234, 234, 234));
        setMaximumSize(new java.awt.Dimension(1400, 800));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setPreferredSize(new java.awt.Dimension(1400, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_Consulta_Orden_Compra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tabla_Consulta_Orden_Compra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla_Consulta_Orden_Compra.setRowHeight(20);
        jScrollPane3.setViewportView(tabla_Consulta_Orden_Compra);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 272, 1300, 440));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        boton_Buscar.setBackground(new java.awt.Color(255, 255, 255));
        boton_Buscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        boton_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario-especialista.png"))); // NOI18N
        boton_Buscar.setText("Proveedor");
        boton_Buscar.setToolTipText("Agregar proveedor");
        boton_Buscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Buscar.setFocusable(false);
        boton_Buscar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Buscar.setMaximumSize(new java.awt.Dimension(125, 37));
        boton_Buscar.setMinimumSize(new java.awt.Dimension(109, 37));
        boton_Buscar.setPreferredSize(new java.awt.Dimension(109, 37));
        jToolBar1.add(boton_Buscar);
        jToolBar1.add(jSeparator2);

        add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Proveedor:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("RUC / CI:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Direccion:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 140, -1, -1));

        campo_Proveedor.setEditable(false);
        campo_Proveedor.setBackground(new java.awt.Color(255, 255, 255));
        campo_Proveedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Proveedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(campo_Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 230, 24));

        campo_RUC.setEditable(false);
        campo_RUC.setBackground(new java.awt.Color(255, 255, 255));
        campo_RUC.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(campo_RUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 170, 24));

        campo_Direccion.setEditable(false);
        campo_Direccion.setBackground(new java.awt.Color(255, 255, 255));
        campo_Direccion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Direccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(campo_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 550, 24));

        boton_Cerrar_Sesion.setBackground(new java.awt.Color(255, 255, 255));
        boton_Cerrar_Sesion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Cerrar_Sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exit-32.png"))); // NOI18N
        boton_Cerrar_Sesion.setText("Cerrar");
        boton_Cerrar_Sesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(boton_Cerrar_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 120, 40));

        etiqueta_Nombre_Usuario.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        etiqueta_Nombre_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        etiqueta_Nombre_Usuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        etiqueta_Nombre_Usuario.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(etiqueta_Nombre_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 180, 40));

        etiqueta_Rol.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        etiqueta_Rol.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(etiqueta_Rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(1134, 20, 147, 20));

        campo_Correo.setEditable(false);
        campo_Correo.setBackground(new java.awt.Color(255, 255, 255));
        campo_Correo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Correo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(campo_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 280, 24));

        campo_Telefono.setEditable(false);
        campo_Telefono.setBackground(new java.awt.Color(255, 255, 255));
        campo_Telefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Telefono.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(campo_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 170, 24));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Correo:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Telefono:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo blanco.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 180, 40));

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Informacion proveedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1360, 170));

        campo_Busqueda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Busqueda.setMaximumSize(new java.awt.Dimension(780, 30));
        campo_Busqueda.setMinimumSize(new java.awt.Dimension(780, 30));
        campo_Busqueda.setPreferredSize(new java.awt.Dimension(780, 30));
        add(campo_Busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 720, 390, -1));

        combo_Filtrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        combo_Filtrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar.....", "Nº Orden de compra", "Nº Factura" }));
        add(combo_Filtrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 720, 180, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Filtrar:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 727, -1, -1));

        jLabel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Compras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 1360, 540));

        combo_Opcion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combo_Opcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar.....", "Compras no ingresadas", "Compras ingresadas" }));
        combo_Opcion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(combo_Opcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 270, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton boton_Buscar;
    public javax.swing.JButton boton_Cerrar_Sesion;
    public javax.swing.JTextField campo_Busqueda;
    private javax.swing.JTextField campo_Correo;
    public javax.swing.JTextField campo_Direccion;
    public javax.swing.JTextField campo_Proveedor;
    public javax.swing.JTextField campo_RUC;
    private javax.swing.JTextField campo_Telefono;
    public javax.swing.JComboBox<String> combo_Filtrar;
    public javax.swing.JComboBox<String> combo_Opcion;
    public javax.swing.JLabel etiqueta_Nombre_Usuario;
    public javax.swing.JLabel etiqueta_Rol;
    public javax.swing.ButtonGroup grupo_Botones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    public javax.swing.JTable tabla_Consulta_Orden_Compra;
    // End of variables declaration//GEN-END:variables
}
