/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Registro_Usuarios;

/**
 *
 * @author David
 */
public class Dialogo_Usuarios extends javax.swing.JDialog {

    /**
     * Creates new form Dialogo_Usuarios
     */
    public Dialogo_Usuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.etiqueta_Nombre.setVisible(false);
        this.etiqueta_Apellido.setVisible(false);
        this.etiqueta_Cedula.setVisible(false);
        this.etiqueta_Correo.setVisible(false);
        this.etiqueta_Usuario.setVisible(false);
        this.etiqueta_Contraseña.setVisible(false);
        this.etiqueta_Repetir_Contraseña.setVisible(false);
        this.etiqueta_Mensaje_Clave.setText("");
        this.etiqueta_Mensaje_Rol.setVisible(false);
        this.etiqueta_Correccion_Cedula.setVisible(false);
        this.etiqueta_Correccion_Usuario.setVisible(false);
        this.etiqueta_Correccion_Cedula.setVisible(false);
        this.etiqueta_Correccion_Usuario.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        campo_Nombre_Registro = new javax.swing.JTextField();
        campo_Apellido_Registro = new javax.swing.JTextField();
        campo_Cedula_Registro = new javax.swing.JTextField();
        campo_Correo_Registro = new javax.swing.JTextField();
        campo_Uusario_Registro = new javax.swing.JTextField();
        campo_Contraseniaa_Registro = new javax.swing.JPasswordField();
        combo_Rol_Registro = new javax.swing.JComboBox<>();
        campo_Recontrasenia_Registro = new javax.swing.JPasswordField();
        etiqueta_Mensaje_Clave = new javax.swing.JLabel();
        etiqueta_Mensaje_Rol = new javax.swing.JLabel();
        etiqueta_Nombre = new javax.swing.JLabel();
        etiqueta_Apellido = new javax.swing.JLabel();
        etiqueta_Cedula = new javax.swing.JLabel();
        etiqueta_Correo = new javax.swing.JLabel();
        etiqueta_Usuario = new javax.swing.JLabel();
        etiqueta_Contraseña = new javax.swing.JLabel();
        etiqueta_Repetir_Contraseña = new javax.swing.JLabel();
        etiqueta_Correccion_Cedula = new javax.swing.JLabel();
        etiqueta_Correccion_Usuario = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        boton_Registro_Usuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(910, 639));
        setMinimumSize(new java.awt.Dimension(910, 639));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Nº Cedula:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Usuario:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 60, 20));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Contraseña:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Correo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Repetir contraseña:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Tipo de Rol:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, -1, -1));

        campo_Nombre_Registro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Nombre_Registro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Nombre_Registro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Nombre_RegistroKeyTyped(evt);
            }
        });
        getContentPane().add(campo_Nombre_Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 355, 25));

        campo_Apellido_Registro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Apellido_Registro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Apellido_Registro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Apellido_RegistroKeyTyped(evt);
            }
        });
        getContentPane().add(campo_Apellido_Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 352, 25));

        campo_Cedula_Registro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Cedula_Registro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Cedula_Registro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Cedula_RegistroKeyTyped(evt);
            }
        });
        getContentPane().add(campo_Cedula_Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 200, 25));

        campo_Correo_Registro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Correo_Registro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Correo_Registro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Correo_RegistroKeyTyped(evt);
            }
        });
        getContentPane().add(campo_Correo_Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 350, 25));

        campo_Uusario_Registro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Uusario_Registro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Uusario_Registro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Uusario_RegistroKeyTyped(evt);
            }
        });
        getContentPane().add(campo_Uusario_Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 190, 25));

        campo_Contraseniaa_Registro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Contraseniaa_Registro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Contraseniaa_Registro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Contraseniaa_RegistroKeyTyped(evt);
            }
        });
        getContentPane().add(campo_Contraseniaa_Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 180, 25));

        combo_Rol_Registro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combo_Rol_Registro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(combo_Rol_Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 210, 25));

        campo_Recontrasenia_Registro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Recontrasenia_Registro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Recontrasenia_Registro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Recontrasenia_RegistroKeyTyped(evt);
            }
        });
        getContentPane().add(campo_Recontrasenia_Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 180, 25));
        getContentPane().add(etiqueta_Mensaje_Clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 220, 15));

        etiqueta_Mensaje_Rol.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etiqueta_Mensaje_Rol.setForeground(java.awt.Color.red);
        etiqueta_Mensaje_Rol.setText("*");
        getContentPane().add(etiqueta_Mensaje_Rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 20, 20));

        etiqueta_Nombre.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etiqueta_Nombre.setForeground(java.awt.Color.red);
        etiqueta_Nombre.setText("*");
        getContentPane().add(etiqueta_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        etiqueta_Apellido.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etiqueta_Apellido.setForeground(java.awt.Color.red);
        etiqueta_Apellido.setText("*");
        getContentPane().add(etiqueta_Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        etiqueta_Cedula.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etiqueta_Cedula.setForeground(java.awt.Color.red);
        etiqueta_Cedula.setText("*");
        getContentPane().add(etiqueta_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        etiqueta_Correo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etiqueta_Correo.setForeground(java.awt.Color.red);
        etiqueta_Correo.setText("*");
        getContentPane().add(etiqueta_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        etiqueta_Usuario.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etiqueta_Usuario.setForeground(java.awt.Color.red);
        etiqueta_Usuario.setText("*");
        getContentPane().add(etiqueta_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        etiqueta_Contraseña.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etiqueta_Contraseña.setForeground(java.awt.Color.red);
        etiqueta_Contraseña.setText("*");
        getContentPane().add(etiqueta_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, -1, -1));

        etiqueta_Repetir_Contraseña.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etiqueta_Repetir_Contraseña.setForeground(java.awt.Color.red);
        etiqueta_Repetir_Contraseña.setText("*");
        getContentPane().add(etiqueta_Repetir_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, -1, -1));

        etiqueta_Correccion_Cedula.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        etiqueta_Correccion_Cedula.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Correccion_Cedula.setText("El numero de cedula ya esta registrado para otro usuario");
        getContentPane().add(etiqueta_Correccion_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 360, -1));

        etiqueta_Correccion_Usuario.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        etiqueta_Correccion_Usuario.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Correccion_Usuario.setText("El usuario ya esta registrado");
        getContentPane().add(etiqueta_Correccion_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        boton_Registro_Usuario.setBackground(new java.awt.Color(255, 255, 255));
        boton_Registro_Usuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Registro_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario guar.png"))); // NOI18N
        boton_Registro_Usuario.setText("Guardar");
        boton_Registro_Usuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Registro_Usuario.setMaximumSize(new java.awt.Dimension(120, 40));
        boton_Registro_Usuario.setMinimumSize(new java.awt.Dimension(120, 40));
        boton_Registro_Usuario.setPreferredSize(new java.awt.Dimension(120, 40));
        jToolBar1.add(boton_Registro_Usuario);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 50));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel1.setText("REGISTRO DE NUEVO USUARIO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campo_Nombre_RegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Nombre_RegistroKeyTyped
        char c = evt.getKeyChar();
        if( c == evt.VK_SPACE && this.campo_Nombre_Registro.getText().length() == 0 ) evt.consume();
        else if(  ( c < 'a' || c > 'z' ) && ( c < 'A' || c>'Z' ) && c != evt.VK_SPACE ){
            evt.consume();
        }
    }//GEN-LAST:event_campo_Nombre_RegistroKeyTyped

    private void campo_Apellido_RegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Apellido_RegistroKeyTyped
        char c = evt.getKeyChar();
        if( c == evt.VK_SPACE && this.campo_Apellido_Registro.getText().length() == 0 ) evt.consume();
        else if(  ( c < 'a' || c > 'z' ) && ( c < 'A' || c>'Z' ) && c != evt.VK_SPACE ){
            evt.consume();
        }
    }//GEN-LAST:event_campo_Apellido_RegistroKeyTyped

    private void campo_Cedula_RegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Cedula_RegistroKeyTyped
        char c = evt.getKeyChar();
        if( c < '0'  || c > '9' || this.campo_Cedula_Registro.getText().length() >= 10 ) evt.consume();
    }//GEN-LAST:event_campo_Cedula_RegistroKeyTyped

    private void campo_Correo_RegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Correo_RegistroKeyTyped
        char c = evt.getKeyChar();
        if ( ( c < 'a' || c > 'z' ) && ( c < 'A' || c >'Z' ) && ( c < '0'  || c > '9' ) && ( c < '#' || c > '&' ) && ( c < '-' || c > '/' ) &&  (  c == evt.VK_SPACE || this.campo_Correo_Registro.getText().contains( "@" ) ) ) evt.consume();
    }//GEN-LAST:event_campo_Correo_RegistroKeyTyped

    private void campo_Uusario_RegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Uusario_RegistroKeyTyped
        char c = evt.getKeyChar();
        if( c == evt.VK_SPACE && this.campo_Uusario_Registro.getText().length() == 0 ) evt.consume();
        else if(  ( c < 'a' || c > 'z' ) && ( c < 'A' || c>'Z' ) && ( c < '0' || c > '9' ) && ( c < '#' || c > '&' ) && c != evt.VK_SPACE ){
            evt.consume();
        }
    }//GEN-LAST:event_campo_Uusario_RegistroKeyTyped

    private void campo_Contraseniaa_RegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Contraseniaa_RegistroKeyTyped
        char c = evt.getKeyChar();
        if( c == evt.VK_SPACE && this.campo_Contraseniaa_Registro.getText().length() == 0 ) evt.consume();
        else if(  ( c < 'a' || c > 'z' ) && ( c < 'A' || c>'Z' ) && ( c < '0' || c > '9' ) && ( c < '#' || c > '&' ) && c != evt.VK_SPACE ){
            evt.consume();
        }
    }//GEN-LAST:event_campo_Contraseniaa_RegistroKeyTyped

    private void campo_Recontrasenia_RegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Recontrasenia_RegistroKeyTyped
        char c = evt.getKeyChar();
        if( c == evt.VK_SPACE && this.campo_Recontrasenia_Registro.getText().length() == 0 ) evt.consume();
        else if(  ( c < 'a' || c > 'z' ) && ( c < 'A' || c>'Z' ) && ( c < '0' || c > '9' ) && ( c < '#' || c > '&' ) && c != evt.VK_SPACE ){
            evt.consume();
        }
    }//GEN-LAST:event_campo_Recontrasenia_RegistroKeyTyped

    public boolean etiquetas() {
        boolean bandera = true;
        
        if (this.campo_Nombre_Registro.getText().matches("[A-Z][a-z]+")) {
            this.etiqueta_Nombre.setVisible(false);
        } else {
            this.etiqueta_Nombre.setVisible(true);
            bandera = false;
        }

        if (this.campo_Apellido_Registro.getText().matches("[A-Z][a-z]+")) {
            this.etiqueta_Apellido.setVisible(false);
        } else {
            this.etiqueta_Apellido.setVisible(true);
            bandera = false;
        }

        if (this.campo_Cedula_Registro.getText().matches("[1-9][0-9]{9}")) {
            this.etiqueta_Cedula.setVisible(false);
        } else {
            this.etiqueta_Cedula.setVisible(true);
            bandera = false;
        }

        if (this.campo_Correo_Registro.getText().matches("[a-zA-Z_\\d]+@[a-zA-Z]+(\\.[a-zA-Z]*)+")) {
            this.etiqueta_Correo.setVisible(false);
        } else {
            this.etiqueta_Correo.setVisible(true);
            bandera = false;
        }

        if (this.campo_Uusario_Registro.getText().matches("[a-zA-Z_\\d]+")) {
            this.etiqueta_Usuario.setVisible(false);
        } else {
            this.etiqueta_Usuario.setVisible(true);
            bandera = false;
        }

        if (this.campo_Contraseniaa_Registro.getText().matches("[a-zA-Z_\\d]+")) {
            this.etiqueta_Contraseña.setVisible(false);
        } else {
            this.etiqueta_Contraseña.setVisible(true);
            bandera = false;
        }

        if (this.campo_Recontrasenia_Registro.getText().matches("[a-zA-Z_\\d]+")) {
            this.etiqueta_Repetir_Contraseña.setVisible(false);
        } else {
            this.etiqueta_Repetir_Contraseña.setVisible(true);
            bandera = false;
        }

        if (this.campo_Contraseniaa_Registro.getText().equals(this.campo_Recontrasenia_Registro.getText())) {
            this.etiqueta_Mensaje_Clave.setText("");
        } else {
            this.etiqueta_Mensaje_Clave.setText("Las claves no coinciden");
        }

        if (this.combo_Rol_Registro.getSelectedIndex() != 0) {
            this.etiqueta_Mensaje_Rol.setVisible(false);
        } else {
            this.etiqueta_Mensaje_Rol.setVisible(true);
            bandera = false;
        }
        return bandera;
    }
    
    public boolean verificar_Etiquetas_Usuario() {
        boolean bandera = true;
        
        if (this.campo_Nombre_Registro.getText().matches("[A-Z][a-z]+")) {
            this.etiqueta_Nombre.setVisible(false);
        } else {
            this.etiqueta_Nombre.setVisible(true);
            bandera = false;
        }

        if (this.campo_Apellido_Registro.getText().matches("[A-Z][a-z]+")) {
            this.etiqueta_Apellido.setVisible(false);
        } else {
            this.etiqueta_Apellido.setVisible(true);
            bandera = false;
        }

        if (this.campo_Cedula_Registro.getText().matches("[1-9][0-9]{9}")) {
            this.etiqueta_Cedula.setVisible(false);
        } else {
            this.etiqueta_Cedula.setVisible(true);
            bandera = false;
        }

        if (this.campo_Correo_Registro.getText().matches("[a-zA-Z_\\d]+@[a-zA-Z]+(\\.[a-zA-Z]*)+")) {
            this.etiqueta_Correo.setVisible(false);
        } else {
            this.etiqueta_Correo.setVisible(true);
            bandera = false;
        }

        if (this.combo_Rol_Registro.getSelectedIndex() != 0) {
            this.etiqueta_Mensaje_Rol.setVisible(false);
        } else {
            this.etiqueta_Mensaje_Rol.setVisible(true);
            bandera = false;
        }
        return bandera;
    }
    
    public void correccion_Campos(String valor){
        if(valor.equals(this.campo_Cedula_Registro.getText())){
            this.etiqueta_Correccion_Cedula.setVisible(true);
        }
        
        if(valor.equals(this.campo_Uusario_Registro.getText())){
            this.etiqueta_Correccion_Usuario.setVisible(true);
        }
    }
    
    public void insertar_Campos_Usuario(String[] valor){
        this.campo_Cedula_Registro.setText(valor[0]);
        this.campo_Nombre_Registro.setText(valor[1]);
        this.campo_Apellido_Registro.setText(valor[2]);
        this.campo_Correo_Registro.setText(valor[3]);
        this.combo_Rol_Registro.setSelectedItem(valor[4]);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dialogo_Usuarios dialog = new Dialogo_Usuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton boton_Registro_Usuario;
    public javax.swing.JTextField campo_Apellido_Registro;
    public javax.swing.JTextField campo_Cedula_Registro;
    public javax.swing.JPasswordField campo_Contraseniaa_Registro;
    public javax.swing.JTextField campo_Correo_Registro;
    public javax.swing.JTextField campo_Nombre_Registro;
    public javax.swing.JPasswordField campo_Recontrasenia_Registro;
    public javax.swing.JTextField campo_Uusario_Registro;
    public javax.swing.JComboBox<String> combo_Rol_Registro;
    private javax.swing.JLabel etiqueta_Apellido;
    private javax.swing.JLabel etiqueta_Cedula;
    private javax.swing.JLabel etiqueta_Contraseña;
    private javax.swing.JLabel etiqueta_Correccion_Cedula;
    private javax.swing.JLabel etiqueta_Correccion_Usuario;
    private javax.swing.JLabel etiqueta_Correo;
    public javax.swing.JLabel etiqueta_Mensaje_Clave;
    public javax.swing.JLabel etiqueta_Mensaje_Rol;
    private javax.swing.JLabel etiqueta_Nombre;
    private javax.swing.JLabel etiqueta_Repetir_Contraseña;
    private javax.swing.JLabel etiqueta_Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
