/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Registro_Usuarios;

/**
 *
 * @author LENOVO
 */
public class Panel_Registro extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Registro
     */
    public Panel_Registro() {
        initComponents();
        this.boton_Modificar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        boton_Nuevo = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        boton_Modificar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        boton_Cerrar_Sesion = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Usuarios = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        campo_Buscar = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        combo_Opciones = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(239, 239, 239));
        setMaximumSize(new java.awt.Dimension(1400, 800));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setPreferredSize(new java.awt.Dimension(1400, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        boton_Nuevo.setBackground(new java.awt.Color(255, 255, 255));
        boton_Nuevo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario add.png"))); // NOI18N
        boton_Nuevo.setText("Nuevo");
        boton_Nuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Nuevo.setFocusable(false);
        boton_Nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_Nuevo.setMaximumSize(new java.awt.Dimension(80, 52));
        boton_Nuevo.setMinimumSize(new java.awt.Dimension(120, 42));
        boton_Nuevo.setPreferredSize(new java.awt.Dimension(120, 42));
        boton_Nuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(boton_Nuevo);
        jToolBar1.add(jSeparator2);
        jToolBar1.add(jSeparator1);

        boton_Modificar.setBackground(new java.awt.Color(255, 255, 255));
        boton_Modificar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario mod.png"))); // NOI18N
        boton_Modificar.setText("Modificar");
        boton_Modificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Modificar.setFocusable(false);
        boton_Modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_Modificar.setMaximumSize(new java.awt.Dimension(80, 52));
        boton_Modificar.setMinimumSize(new java.awt.Dimension(120, 42));
        boton_Modificar.setPreferredSize(new java.awt.Dimension(120, 42));
        boton_Modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(boton_Modificar);
        jToolBar1.add(jSeparator3);

        add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 85, 800));

        boton_Cerrar_Sesion.setBackground(new java.awt.Color(255, 255, 255));
        boton_Cerrar_Sesion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Cerrar_Sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exit-32.png"))); // NOI18N
        boton_Cerrar_Sesion.setText("Cerrar");
        boton_Cerrar_Sesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(boton_Cerrar_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, 100, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo blanco.png"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 200, 40));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 390));

        tabla_Usuarios.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tabla_Usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Correo", "Rol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_Usuarios);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 1310, 760));

        jToolBar2.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar2.setRollover(true);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search_locate_find_6278.png"))); // NOI18N
        jLabel1.setText("    ");
        jToolBar2.add(jLabel1);

        campo_Buscar.setEditable(false);
        campo_Buscar.setBackground(new java.awt.Color(255, 255, 255));
        campo_Buscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Buscar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Buscar.setMaximumSize(new java.awt.Dimension(550, 30));
        campo_Buscar.setMinimumSize(new java.awt.Dimension(550, 30));
        campo_Buscar.setPreferredSize(new java.awt.Dimension(550, 30));
        campo_Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_BuscarKeyTyped(evt);
            }
        });
        jToolBar2.add(campo_Buscar);
        jToolBar2.add(jSeparator4);

        combo_Opciones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combo_Opciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar.....", "Por CI", "Por nombre", "Por rol" }));
        combo_Opciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar2.add(combo_Opciones);

        add(jToolBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 1010, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void campo_BuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_BuscarKeyTyped

    }//GEN-LAST:event_campo_BuscarKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton boton_Cerrar_Sesion;
    public javax.swing.JButton boton_Modificar;
    public javax.swing.JButton boton_Nuevo;
    public javax.swing.JTextField campo_Buscar;
    public javax.swing.JComboBox<String> combo_Opciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    public javax.swing.JTable tabla_Usuarios;
    // End of variables declaration//GEN-END:variables
}
