/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Cliente;

import Controlador.PlaceHolder_Textos;
import Modelo.Cliente;
import java.text.DecimalFormat;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author David
 */
public class Dialogo_Registrar_Cliente extends javax.swing.JDialog {

    /**
     * Creates new form Dialogo_Registrar_Cliente
     */
    public Dialogo_Registrar_Cliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.grupo_Botones_DNI.add(this.radio_Boton_CI);
        this.grupo_Botones_DNI.add(this.radio_Boton_RUC);
        this.campo_RUC.setEditable(false);
        this.etiqueta_Indicador_Ciudad.setVisible(false);
        this.etiqueta_Indicador_RUC.setVisible(false);
        this.etiqueta_Indicador_Direccion.setVisible(false);
        this.etiqueta_Indicador_Telefono.setVisible(false);
        this.etiqueta_Indicador_Celular.setVisible(false);
        this.etiqueta_Indicador_Correo.setVisible(false);
        this.etiqueta_Indicador_Contacto.setVisible(false);
        this.etiqueta_Indicador_Cliente.setVisible(false);
        this.etiqueta_Correccion_RUC.setVisible(false);
        this.etiqueta_Correccion_Correo.setVisible(false);
        AutoCompleteDecorator.decorate(this.campo_Ciudad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_Botones_DNI = new javax.swing.ButtonGroup();
        etiqueta_Cliente = new javax.swing.JLabel();
        etiqueta_Ciudad = new javax.swing.JLabel();
        etiqueta_RUC = new javax.swing.JLabel();
        campo_RUC = new javax.swing.JTextField();
        etiqueta_Direccion = new javax.swing.JLabel();
        campo_Direccion = new javax.swing.JTextField();
        campo_Telefono = new javax.swing.JTextField();
        etiqueta_Telefono = new javax.swing.JLabel();
        etiqueta_Correo = new javax.swing.JLabel();
        campo_Correo = new javax.swing.JTextField();
        campo_Contacto = new javax.swing.JTextField();
        etiqueta_Persona1 = new javax.swing.JLabel();
        etiqueta_Persona2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campo_Celular = new javax.swing.JTextField();
        etiqueta_Indicador_Direccion = new javax.swing.JLabel();
        etiqueta_Indicador_Telefono = new javax.swing.JLabel();
        etiqueta_Indicador_Ciudad = new javax.swing.JLabel();
        etiqueta_Indicador_Celular = new javax.swing.JLabel();
        etiqueta_Indicador_Correo = new javax.swing.JLabel();
        etiqueta_Indicador_RUC = new javax.swing.JLabel();
        etiqueta_Indicador_Contacto = new javax.swing.JLabel();
        combo_Cliente = new javax.swing.JTextField();
        etiqueta_Indicador_Cliente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        campo_Cod_Cliente = new javax.swing.JTextField();
        radio_Boton_CI = new javax.swing.JRadioButton();
        radio_Boton_RUC = new javax.swing.JRadioButton();
        campo_Ciudad = new javax.swing.JComboBox<>();
        etiqueta_Correccion_RUC = new javax.swing.JLabel();
        etiqueta_Correccion_Correo = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        boton_Agregar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Datos cliente");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(826, 601));
        setMinimumSize(new java.awt.Dimension(826, 601));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiqueta_Cliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_Cliente.setText("Cliente:");
        getContentPane().add(etiqueta_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 134, -1, -1));

        etiqueta_Ciudad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_Ciudad.setText("Ciudad:");
        getContentPane().add(etiqueta_Ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 324, -1, -1));

        etiqueta_RUC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_RUC.setText("R.U.C/ CI:");
        getContentPane().add(etiqueta_RUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 190, -1, -1));

        campo_RUC.setEditable(false);
        campo_RUC.setBackground(new java.awt.Color(255, 255, 255));
        campo_RUC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_RUC.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_RUC.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        campo_RUC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campo_RUCMouseClicked(evt);
            }
        });
        campo_RUC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_RUCKeyTyped(evt);
            }
        });
        getContentPane().add(campo_RUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 186, 210, 24));

        etiqueta_Direccion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_Direccion.setText("Direccion:");
        getContentPane().add(etiqueta_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 380, -1, -1));

        campo_Direccion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Direccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Direccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campo_DireccionMouseClicked(evt);
            }
        });
        campo_Direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_DireccionKeyTyped(evt);
            }
        });
        getContentPane().add(campo_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 410, 24));

        campo_Telefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Telefono.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Telefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campo_TelefonoMouseClicked(evt);
            }
        });
        campo_Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_TelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(campo_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 180, 24));

        etiqueta_Telefono.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_Telefono.setText("Telefono:");
        getContentPane().add(etiqueta_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 262, -1, -1));

        etiqueta_Correo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_Correo.setText("Correo:");
        getContentPane().add(etiqueta_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        campo_Correo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Correo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Correo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campo_CorreoMouseClicked(evt);
            }
        });
        campo_Correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_CorreoKeyTyped(evt);
            }
        });
        getContentPane().add(campo_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 330, 24));

        campo_Contacto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Contacto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Contacto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campo_ContactoMouseClicked(evt);
            }
        });
        campo_Contacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_ContactoKeyTyped(evt);
            }
        });
        getContentPane().add(campo_Contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 330, 24));

        etiqueta_Persona1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        etiqueta_Persona1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_Persona1.setText("Persona de");
        getContentPane().add(etiqueta_Persona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, 20));

        etiqueta_Persona2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        etiqueta_Persona2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_Persona2.setText(" contacto:");
        getContentPane().add(etiqueta_Persona2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Celular:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 262, -1, -1));

        campo_Celular.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Celular.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Celular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campo_CelularMouseClicked(evt);
            }
        });
        campo_Celular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_CelularKeyTyped(evt);
            }
        });
        getContentPane().add(campo_Celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 157, 24));

        etiqueta_Indicador_Direccion.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Direccion.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Direccion.setText("*");
        getContentPane().add(etiqueta_Indicador_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 376, -1, -1));

        etiqueta_Indicador_Telefono.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Telefono.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Telefono.setText("*");
        getContentPane().add(etiqueta_Indicador_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 256, -1, -1));

        etiqueta_Indicador_Ciudad.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Ciudad.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Ciudad.setText("*");
        getContentPane().add(etiqueta_Indicador_Ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 320, -1, -1));

        etiqueta_Indicador_Celular.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Celular.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Celular.setText("*");
        getContentPane().add(etiqueta_Indicador_Celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 256, -1, -1));

        etiqueta_Indicador_Correo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Correo.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Correo.setText("*");
        getContentPane().add(etiqueta_Indicador_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 436, 20, -1));

        etiqueta_Indicador_RUC.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_RUC.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_RUC.setText("*");
        getContentPane().add(etiqueta_Indicador_RUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 182, -1, -1));

        etiqueta_Indicador_Contacto.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Contacto.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Contacto.setText("*");
        getContentPane().add(etiqueta_Indicador_Contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 502, -1, -1));

        combo_Cliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combo_Cliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        combo_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combo_ClienteMouseClicked(evt);
            }
        });
        combo_Cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                combo_ClienteKeyTyped(evt);
            }
        });
        getContentPane().add(combo_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 330, 24));

        etiqueta_Indicador_Cliente.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Cliente.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Cliente.setText("*");
        getContentPane().add(etiqueta_Indicador_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Cod. Cliente:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        campo_Cod_Cliente.setEditable(false);
        campo_Cod_Cliente.setBackground(new java.awt.Color(255, 255, 255));
        campo_Cod_Cliente.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        campo_Cod_Cliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Cod_Cliente.setMaximumSize(new java.awt.Dimension(2, 20));
        campo_Cod_Cliente.setMinimumSize(new java.awt.Dimension(2, 20));
        campo_Cod_Cliente.setPreferredSize(new java.awt.Dimension(2, 20));
        campo_Cod_Cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Cod_ClienteKeyTyped(evt);
            }
        });
        getContentPane().add(campo_Cod_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 75, 170, 24));

        radio_Boton_CI.setBackground(new java.awt.Color(255, 255, 255));
        radio_Boton_CI.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        radio_Boton_CI.setText("Cedula");
        radio_Boton_CI.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        radio_Boton_CI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_Boton_CIActionPerformed(evt);
            }
        });
        getContentPane().add(radio_Boton_CI, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 178, -1, -1));

        radio_Boton_RUC.setBackground(new java.awt.Color(255, 255, 255));
        radio_Boton_RUC.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        radio_Boton_RUC.setText("RUC");
        radio_Boton_RUC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        radio_Boton_RUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_Boton_RUCActionPerformed(evt);
            }
        });
        getContentPane().add(radio_Boton_RUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 198, -1, -1));

        campo_Ciudad.setEditable(true);
        campo_Ciudad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Ciudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuenca", "Camilo Ponce Enríquez", "Chordeleg", "El Pan", "Girón", "Guachapala", "Gualaceo", "Nabón", "Oña", "Paute", "Pucará", "San Fernando", "Santa Isabel", "Sevilla de Oro", "Sígsig", "Guaranda", "Caluma", "Chillanes", "Chimbo", "Echeandía", "Las Naves", "San Miguel", "Cantón Azogues", "Biblián", "Cañar", "Déleg", "El Tambo", "La Troncal", "Suscal", "Tulcán", "Bolívar", "Espejo", "Mira", "Montúfar", "Huaca", "Riobamba", "Alausí", "Chambo", "Chunchi", "Colta", "Cumandá", "Guamote", "Guano", "Pallatanga", "Penipe", "Latacunga", "La Maná", "Pangua", "Pujilí", "Salcedo", "Saquisilí", "Sigchos", "Machala", "Arenillas", "Atahualpa", "Balsas", "Chilla", "El Guabo", "Huaquillas", "Las Lajas", "Marcabelí", "Pasaje", "Piñas", "Portovelo", "Santa Rosa", "Zaruma", "Esmeraldas", "Atacames", "Eloy Alfaro", "Muisne", "Quinindé", "Rioverde", "San Lorenzo", "San Cristóbal", "Isabela", "Santa Cruz", "Guayaquil", "Alfredo Baquerizo", "Balao", "Balzar", "Colimes", "Daule", "Durán", "El Empalme", "El Triunfo", "General Antonio Elizalde", "Isidro Ayora", "Lomas de Sargentillo", "Marcelino Maridueña", "Milagro", "Naranjal", "Naranjito", "Ibarra", "Antonio Ante", "Cotacachi", "Otavalo", "Pimampiro", "San Miguel de Urcuquí", "Loja", "Calvas", "Catamayo", "Celica", "Chaguarpamba", "Espíndola", "Gonzanamá", "Macará", "Olmedo", "Paltas", "Pindal", "Puyango", "Quilanga", "Saraguro", "Sozoranga", "Zapotillo", "Babahoyo", "Baba", "Buena Fe", "Mocache", "Montalvo", "Palenque", "Puebloviejo", "Quevedo", "Quinsaloma", "Urdaneta", "Valencia", "Ventanas", "Vinces", "Portoviejo", "24 de Mayo", "Bolívar", "Chone", "El Carmen", "Flavio Alfaro", "Jama", "Jaramijó", "Jipijapa", "Junín", "Manta", "Montecristi", "Olmedo", "Paján", "Pedernales", "Pichincha", "Puerto López", "Rocafuerte", "San Vicente", "Santa Ana", "Sucre", "Tosagua", "Morona", "Gualaquiza", "Huamboya", "Limón Indanza", "Logroño", "Pablo Sexto", "Palora", "San Juan Bosco", "Santiago de Méndez", "Sucúa", "Taisha", "Tiwintza", "Tena", "Archidona", "Carlos Julio Arosemena Tola", "El Chaco", "Quijos", "Francisco de Orellana", "Aguarico", "La Joya de los Sachas", "Loreto", "Pastaza", "Arajuno", "Mera", "Santa Clara", "Quito", "Cayambe", "Mejía", "Pedro Moncayo", "Pedro Vicente Maldonado", "Puerto Quito", "Rumiñahui", "San Miguel de los Bancos", "Santa Elena", "La Libertad", "Salinas", "Santo Domingo", "La Concordia", "Lago Agrio", "Cascales", "Cuyabeno", "Gonzalo Pizarro", "Putumayo", "Shushufindi", "Sucumbíos", "Ambato", "Baños", "Cevallos", "Mocha", "Patate", "Quero", "San Pedro de Pelileo", "Santiago de Píllaro", "Tisaleo", "Zamora", "Centinela del Cóndor", "Chinchipe", "El Pangui", "Nangaritza", "Palanda", "Paquisha", "Yacuambi", "Yantzaza", "Nobol", "Palestina", "Pedro Carbo", "Playas", "Salitre", "Samborondón", "Santa Lucía", "Simón Bolívar", "Yaguachi" }));
        campo_Ciudad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Ciudad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                campo_CiudadItemStateChanged(evt);
            }
        });
        campo_Ciudad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_CiudadFocusGained(evt);
            }
        });
        campo_Ciudad.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                campo_CiudadMouseWheelMoved(evt);
            }
        });
        campo_Ciudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campo_CiudadMouseClicked(evt);
            }
        });
        getContentPane().add(campo_Ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 180, 24));

        etiqueta_Correccion_RUC.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        etiqueta_Correccion_RUC.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Correccion_RUC.setText("El RUC/CI ya se encuentra registrado para otro cliente");
        getContentPane().add(etiqueta_Correccion_RUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 310, -1));

        etiqueta_Correccion_Correo.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        etiqueta_Correccion_Correo.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Correccion_Correo.setText("El Correo ya se encuentra registrado para otro cliente");
        getContentPane().add(etiqueta_Correccion_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 310, -1));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        boton_Agregar.setBackground(java.awt.Color.white);
        boton_Agregar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton-anadir-usuario (1).png"))); // NOI18N
        boton_Agregar.setText("Guardar");
        boton_Agregar.setToolTipText("Guardar cliente");
        boton_Agregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Agregar.setFocusable(false);
        boton_Agregar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Agregar.setMaximumSize(new java.awt.Dimension(100, 57));
        boton_Agregar.setMinimumSize(new java.awt.Dimension(100, 57));
        boton_Agregar.setPreferredSize(new java.awt.Dimension(100, 57));
        boton_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_AgregarActionPerformed(evt);
            }
        });
        jToolBar1.add(boton_Agregar);
        jToolBar1.add(jSeparator1);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_AgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_AgregarActionPerformed

    private void campo_CorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_CorreoKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < '0' || c > '9') && (c < '#' || c > '&') && (c < '-' || c > '/') && (c == evt.VK_SPACE || this.campo_Correo.getText().contains("@"))) {
            evt.consume();
        }
    }//GEN-LAST:event_campo_CorreoKeyTyped

    private void campo_TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_TelefonoKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9' || this.campo_Telefono.getText().length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_campo_TelefonoKeyTyped

    private void radio_Boton_RUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_Boton_RUCActionPerformed
        this.campo_RUC.setEditable(true);
        this.campo_RUC.setText("");
    }//GEN-LAST:event_radio_Boton_RUCActionPerformed

    private void campo_DireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_DireccionKeyTyped
        char c = evt.getKeyChar();
        if (c == evt.VK_SPACE && this.campo_Direccion.getText().length() == 0) {
            evt.consume();
        } else if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < '0' || c > '9') && (c < '-' || c > '.') && c != evt.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_campo_DireccionKeyTyped

    private void radio_Boton_CIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_Boton_CIActionPerformed
        this.campo_RUC.setEditable(true);
        this.campo_RUC.setText("");
    }//GEN-LAST:event_radio_Boton_CIActionPerformed

    private void campo_RUCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_RUCKeyTyped
        char c = evt.getKeyChar();

        if (this.radio_Boton_RUC.isSelected()) {
            if (c < '0' || c > '9' || this.campo_RUC.getText().length() >= 13) {
                evt.consume();
            }
        }

        if (this.radio_Boton_CI.isSelected()) {
            if (c < '0' || c > '9' || this.campo_RUC.getText().length() >= 10) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_campo_RUCKeyTyped

    private void campo_CelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_CelularKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9' || this.campo_Celular.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_campo_CelularKeyTyped

    private void campo_ContactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_ContactoKeyTyped
        char c = evt.getKeyChar();
        if (c == evt.VK_SPACE && this.campo_Contacto.getText().length() == 0) {
            evt.consume();
        } else if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && c != evt.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_campo_ContactoKeyTyped

    private void combo_ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo_ClienteMouseClicked
        this.colores_Bordes();
        combo_Cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 180, 20)));
    }//GEN-LAST:event_combo_ClienteMouseClicked

    private void campo_CelularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_CelularMouseClicked
        this.colores_Bordes();
        this.campo_Celular.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 180, 20)));
    }//GEN-LAST:event_campo_CelularMouseClicked

    private void campo_RUCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_RUCMouseClicked
        if (this.radio_Boton_CI.isSelected() || this.radio_Boton_RUC.isSelected()) {
            this.colores_Bordes();
            this.campo_RUC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 180, 20)));
        }
    }//GEN-LAST:event_campo_RUCMouseClicked

    private void campo_TelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_TelefonoMouseClicked
        this.colores_Bordes();
        this.campo_Telefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 180, 20)));
    }//GEN-LAST:event_campo_TelefonoMouseClicked

    private void campo_DireccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_DireccionMouseClicked
        this.colores_Bordes();
        this.campo_Direccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 180, 20)));
    }//GEN-LAST:event_campo_DireccionMouseClicked

    private void campo_CorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_CorreoMouseClicked
        this.colores_Bordes();
        this.campo_Correo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 180, 20)));
    }//GEN-LAST:event_campo_CorreoMouseClicked

    private void campo_ContactoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_ContactoMouseClicked
        this.colores_Bordes();
        this.campo_Contacto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 180, 20)));
    }//GEN-LAST:event_campo_ContactoMouseClicked

    private void campo_CiudadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_CiudadMouseClicked

    }//GEN-LAST:event_campo_CiudadMouseClicked

    private void campo_CiudadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_CiudadFocusGained
        
    }//GEN-LAST:event_campo_CiudadFocusGained

    private void campo_CiudadMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_campo_CiudadMouseWheelMoved
        this.colores_Bordes();
    }//GEN-LAST:event_campo_CiudadMouseWheelMoved

    private void campo_CiudadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_campo_CiudadItemStateChanged
        this.colores_Bordes();
    }//GEN-LAST:event_campo_CiudadItemStateChanged

    private void campo_Cod_ClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Cod_ClienteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_Cod_ClienteKeyTyped

    private void combo_ClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combo_ClienteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_ClienteKeyTyped

    public boolean etiquetas() {
        boolean bandera = true;
        
        if (this.combo_Cliente.getText().isEmpty()) {
            this.etiqueta_Indicador_Cliente.setVisible(true);
            bandera = false;
        } else {
            this.etiqueta_Indicador_Cliente.setVisible(false);
        }

        if (this.campo_Ciudad.getSelectedIndex() == - 1) {
            this.etiqueta_Indicador_Ciudad.setVisible(true);
            bandera = false;
        } else {
            this.etiqueta_Indicador_Ciudad.setVisible(false);
        }

        if( this.campo_RUC.getText().matches( "[0-9][0-9]{12}" ) && this.radio_Boton_RUC.isSelected() ){
            this.etiqueta_Indicador_RUC.setVisible( false );
        }else if(this.campo_RUC.getText().matches( "[0-9][0-9]{9}" ) && this.radio_Boton_CI.isSelected()){
            this.etiqueta_Indicador_RUC.setVisible( false );
        }
        else{
            this.etiqueta_Indicador_RUC.setVisible( true );
            bandera = false;
        }

        if (this.campo_Direccion.getText().isEmpty()) {
            this.etiqueta_Indicador_Direccion.setVisible(true);
            bandera = false;
        } else {
            this.etiqueta_Indicador_Direccion.setVisible(false);
        }	

        if (this.campo_Telefono.getText().matches("[0][1-9][0-9]{7}")) {
            this.etiqueta_Indicador_Telefono.setVisible(false);
        } else {
            this.etiqueta_Indicador_Telefono.setVisible(true);
            bandera = false;
        }

        if (this.campo_Celular.getText().matches("[0][8-9][0-9]{8}")) {
            this.etiqueta_Indicador_Celular.setVisible(false);
        } else {
            this.etiqueta_Indicador_Celular.setVisible(true);
            bandera = false;
        }

        if (this.campo_Correo.getText().matches("[a-zA-Z_\\d]+@[a-zA-Z]+(\\.[a-zA-Z]*)+")) {
            this.etiqueta_Indicador_Correo.setVisible(false);
        } else {
            this.etiqueta_Indicador_Correo.setVisible(true);
            bandera = false;
        }

        if (this.campo_Contacto.getText().isEmpty()) {
            this.etiqueta_Indicador_Contacto.setVisible(true);
            bandera = false;
        } else {
            this.etiqueta_Indicador_Contacto.setVisible(false);
        }
        return bandera;
    }
    
    public void numero_Cliente(String numero) {
        if (numero == null) {
            this.campo_Cod_Cliente.setText(convertirNumero(0));
        } else {
            this.campo_Cod_Cliente.setText(convertirNumero(Integer.parseInt(numero)));
        }
    }
    
    public String convertirNumero(int numero) {
        DecimalFormat format = new DecimalFormat("00000000");
        return format.format(numero + 1);
    }
    
    public void correccion_Campos(String valor){
        if(valor.equals(this.campo_RUC.getText())){
            this.etiqueta_Correccion_RUC.setVisible(true);
        }
        
        if(valor.equals(this.campo_Correo.getText())){
            this.etiqueta_Correccion_Correo.setVisible(true);
        }
    }
    
    public void cargar_Datos_Cliente(Cliente cliente){
        this.campo_Cod_Cliente.setText(cliente.getCodigo_Cliente());
        this.combo_Cliente.setText(cliente.getCliente());
        this.campo_RUC.setText(cliente.getRUC());
        this.campos_Busqueda();
        this.campo_Telefono.setText(cliente.getTelefono());
        this.campo_Celular.setText(cliente.getCelular());
        this.campo_Ciudad.setSelectedItem(cliente.getCiudad());
        this.campo_Direccion.setText(cliente.getDireccion());
        this.campo_Correo.setText(cliente.getCorreo());
        this.campo_Contacto.setText(cliente.getPersona_Contacto());
    }
    
    public void campos_Busqueda() {
        if (this.campo_RUC.getText().length() == 10) {
            this.radio_Boton_CI.setSelected(true);
        } else if (this.campo_RUC.getText().length() == 13) {
            this.radio_Boton_RUC.setSelected(true);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Registrar_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Registrar_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Registrar_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Registrar_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dialogo_Registrar_Cliente dialog = new Dialogo_Registrar_Cliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void colores_Bordes() {
        this.combo_Cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        this.campo_Celular.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        this.campo_Contacto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        this.campo_Correo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        this.campo_Direccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        this.campo_RUC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        this.campo_Telefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton boton_Agregar;
    public javax.swing.JTextField campo_Celular;
    public javax.swing.JComboBox<String> campo_Ciudad;
    public javax.swing.JTextField campo_Cod_Cliente;
    public javax.swing.JTextField campo_Contacto;
    public javax.swing.JTextField campo_Correo;
    public javax.swing.JTextField campo_Direccion;
    public javax.swing.JTextField campo_RUC;
    public javax.swing.JTextField campo_Telefono;
    public javax.swing.JTextField combo_Cliente;
    public javax.swing.JLabel etiqueta_Ciudad;
    public javax.swing.JLabel etiqueta_Cliente;
    private javax.swing.JLabel etiqueta_Correccion_Correo;
    private javax.swing.JLabel etiqueta_Correccion_RUC;
    public javax.swing.JLabel etiqueta_Correo;
    public javax.swing.JLabel etiqueta_Direccion;
    private javax.swing.JLabel etiqueta_Indicador_Celular;
    private javax.swing.JLabel etiqueta_Indicador_Ciudad;
    private javax.swing.JLabel etiqueta_Indicador_Cliente;
    private javax.swing.JLabel etiqueta_Indicador_Contacto;
    private javax.swing.JLabel etiqueta_Indicador_Correo;
    private javax.swing.JLabel etiqueta_Indicador_Direccion;
    private javax.swing.JLabel etiqueta_Indicador_RUC;
    private javax.swing.JLabel etiqueta_Indicador_Telefono;
    public javax.swing.JLabel etiqueta_Persona1;
    public javax.swing.JLabel etiqueta_Persona2;
    public javax.swing.JLabel etiqueta_RUC;
    public javax.swing.JLabel etiqueta_Telefono;
    public javax.swing.ButtonGroup grupo_Botones_DNI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JRadioButton radio_Boton_CI;
    private javax.swing.JRadioButton radio_Boton_RUC;
    // End of variables declaration//GEN-END:variables
}
