/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Orden_De_Compra;

import Modelo.Orden_Compra;
import Modelo.Proveedor;
import Modelo.Usuario;
import java.awt.Color;
import java.awt.Font;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author David
 */
public class Panel_Orden_Compra extends javax.swing.JPanel {

    private DefaultTableModel       modelo_Tabla_Datos_Compras;
    private DecimalFormat           formato_Numero = new DecimalFormat("#.00", new DecimalFormatSymbols(Locale.US));
    /**
     * Creates new form Panel_Cotizacion
     */
    public Panel_Orden_Compra() {
        initComponents();
        //calendario_Orden_Compra.setDate( new Date() );
        //this.modelo_Tabla_Datos_Compras = ( DefaultTableModel )  this.tabla_Productos_Orden_Compra.getModel();
        /*this.tabla_Productos_Orden_Compra.getTableHeader().setFont( new Font( "Arial", Font.BOLD, 14 ) );
        this.tabla_Productos_Orden_Compra.getTableHeader().setBackground( new Color( 32, 136, 203 ) );
        this.tabla_Productos_Orden_Compra.getTableHeader().setForeground( new Color( 255, 255, 255) );      
        this.etiqueta_Indicador_Proveedor.setVisible( false );
        this.etiqueta_Indicador_RUC.setVisible( false );
        this.etiqueta_Indicador_Direccion.setVisible( false );
        this.etiqueta_Indicador_Telefono.setVisible( false );
        this.etiqueta_Indicador_Correo.setVisible( false );
        this.etiqueta_Indicador_Contacto.setVisible( false );
        this.etiqueta_Indicador_Modalidad.setVisible( false );
        this.etiqueta_Indicador_Estado.setVisible( false );*/
        this.boton_Modificar_Orden_Compra.setEnabled( false );
        //this.boton_Agregar_Fila.setEnabled(false);
        //this.boton_Quitar_Fila.setEnabled(false);
        this.boton_Generar_Orden.setEnabled(false);
        //this.etiqueta_Indicador_Calendario.setVisible(false);
        //this.tabla_Productos_Orden_Compra.getTableHeader().setReorderingAllowed(false) ;
        //this.valor_IVA.setValue(12);
        //this.valor_IVA.setEnabled(false);
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        this.tabla_Consulta_Compra.getColumnModel().getColumn(0).setCellRenderer(tcr);
        this.tabla_Consulta_Compra.getColumnModel().getColumn(4).setCellRenderer(tcr);
        this.campo_Busqueda.setEditable(false);
        this.tabla_Consulta_Compra.getTableHeader().setReorderingAllowed(false) ;
        this.fecha_1.setVisible(false);
        this.fecha_2.setVisible(false);
        this.boton_Fecha.setVisible(false);
        this.fecha_1.setDate( new Date() );
        this.fecha_2.setDate( new Date() );
        this.etiqueta_Error_Fecha.setVisible(false);
    }
    
    public void Roles(String rol) {
        if (rol.equals("Vendedor")) {
            boolean[] bandera = {true, true, true, true, true, true, false};
            this.habilitar_Rol(bandera);
        }
        
        if (rol.equals("Bodeguero")) {
            boolean[] bandera = {false, false, false, false, false, false, false};
            this.habilitar_Rol(bandera);
        }
        
        if (rol.equals("Contador")) {
            boolean[] bandera = {false, false, false, false, false, false, false};
            this.habilitar_Rol(bandera);
        }
        
        if (rol.equals("Administrador")) {
            boolean[] bandera = {true, true, true, true, true, true, true};
            this.habilitar_Rol(bandera);
        }
    }
    
    public void habilitar_Rol(boolean[] bandera) {
        this.boton_Nueva_Orden_Compra.setVisible(bandera[0]);
        //this.boton_Guardar_Orden_Compra.setVisible(bandera[1]);
        this.boton_Modificar_Orden_Compra.setVisible(bandera[2]);
        //this.boton_Buscar_Proveedor_Orden.setVisible(bandera[3]);
        //this.boton_Agregar_Fila.setVisible(bandera[4]);
        //this.boton_Quitar_Fila.setVisible(bandera[5]);
        //this.combo_Estado_Orden.setVisible(bandera[6]);
        //this.etiqueta_Estado_Combo.setVisible(bandera[6]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        boton_Nueva_Orden_Compra = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        boton_Modificar_Orden_Compra = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        boton_Generar_Orden = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        boton_Cerrar_Sesion = new javax.swing.JButton();
        etiqueta_Rol = new javax.swing.JLabel();
        etiqueta_Nombre_Usuario = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        campo_Busqueda = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        fecha_1 = new com.toedter.calendar.JDateChooser();
        fecha_2 = new com.toedter.calendar.JDateChooser();
        etiqueta_Error_Fecha = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        boton_Fecha = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        combo_Opciones = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Consulta_Compra = new javax.swing.JTable();

        setBackground(new java.awt.Color(229, 229, 229));
        setMaximumSize(new java.awt.Dimension(1400, 800));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setPreferredSize(new java.awt.Dimension(1400, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator1);

        boton_Nueva_Orden_Compra.setBackground(new java.awt.Color(255, 255, 255));
        boton_Nueva_Orden_Compra.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Nueva_Orden_Compra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-archivo.png"))); // NOI18N
        boton_Nueva_Orden_Compra.setText("Nuevo");
        boton_Nueva_Orden_Compra.setToolTipText("Nueva cotizacion");
        boton_Nueva_Orden_Compra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Nueva_Orden_Compra.setFocusable(false);
        boton_Nueva_Orden_Compra.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Nueva_Orden_Compra.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Nueva_Orden_Compra.setMinimumSize(new java.awt.Dimension(100, 37));
        boton_Nueva_Orden_Compra.setPreferredSize(new java.awt.Dimension(100, 37));
        boton_Nueva_Orden_Compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Nueva_Orden_CompraActionPerformed(evt);
            }
        });
        jToolBar1.add(boton_Nueva_Orden_Compra);
        jToolBar1.add(jSeparator2);

        boton_Modificar_Orden_Compra.setBackground(new java.awt.Color(255, 255, 255));
        boton_Modificar_Orden_Compra.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Modificar_Orden_Compra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar-documento.png"))); // NOI18N
        boton_Modificar_Orden_Compra.setText("Modificar");
        boton_Modificar_Orden_Compra.setToolTipText("Editar cotizacion");
        boton_Modificar_Orden_Compra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Modificar_Orden_Compra.setFocusable(false);
        boton_Modificar_Orden_Compra.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Modificar_Orden_Compra.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Modificar_Orden_Compra.setMinimumSize(new java.awt.Dimension(60, 37));
        boton_Modificar_Orden_Compra.setPreferredSize(new java.awt.Dimension(60, 37));
        boton_Modificar_Orden_Compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Modificar_Orden_CompraActionPerformed(evt);
            }
        });
        jToolBar1.add(boton_Modificar_Orden_Compra);
        jToolBar1.add(jSeparator3);

        boton_Generar_Orden.setBackground(new java.awt.Color(255, 255, 255));
        boton_Generar_Orden.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Generar_Orden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportar 1.png"))); // NOI18N
        boton_Generar_Orden.setText("Reporte");
        boton_Generar_Orden.setToolTipText("Generar cotizacion");
        boton_Generar_Orden.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Generar_Orden.setFocusable(false);
        boton_Generar_Orden.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Generar_Orden.setMaximumSize(new java.awt.Dimension(100, 37));
        boton_Generar_Orden.setMinimumSize(new java.awt.Dimension(100, 37));
        boton_Generar_Orden.setPreferredSize(new java.awt.Dimension(100, 37));
        jToolBar1.add(boton_Generar_Orden);
        jToolBar1.add(jSeparator4);
        jToolBar1.add(jSeparator6);

        add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 800));

        boton_Cerrar_Sesion.setBackground(new java.awt.Color(255, 255, 255));
        boton_Cerrar_Sesion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Cerrar_Sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exit-32.png"))); // NOI18N
        boton_Cerrar_Sesion.setText("Cerrar");
        boton_Cerrar_Sesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(boton_Cerrar_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 120, 40));

        etiqueta_Rol.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        etiqueta_Rol.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(etiqueta_Rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(1134, 20, 147, 20));

        etiqueta_Nombre_Usuario.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        etiqueta_Nombre_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        etiqueta_Nombre_Usuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        etiqueta_Nombre_Usuario.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(etiqueta_Nombre_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 180, 40));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo blanco.png"))); // NOI18N
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 180, 40));

        jToolBar2.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar2.setRollover(true);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        jLabel1.setText("   ");
        jToolBar2.add(jLabel1);

        campo_Busqueda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Busqueda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Busqueda.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        campo_Busqueda.setMaximumSize(new java.awt.Dimension(450, 30));
        campo_Busqueda.setMinimumSize(new java.awt.Dimension(450, 30));
        campo_Busqueda.setPreferredSize(new java.awt.Dimension(450, 30));
        jToolBar2.add(campo_Busqueda);
        jToolBar2.add(jSeparator5);

        fecha_1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Desde", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        fecha_1.setDateFormatString("yyyy-MM-dd");
        jToolBar2.add(fecha_1);

        fecha_2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hasta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        fecha_2.setDateFormatString("yyyy-MM-dd");
        jToolBar2.add(fecha_2);

        etiqueta_Error_Fecha.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etiqueta_Error_Fecha.setForeground(new java.awt.Color(204, 0, 51));
        etiqueta_Error_Fecha.setText("*");
        jToolBar2.add(etiqueta_Error_Fecha);
        jToolBar2.add(jSeparator7);

        boton_Fecha.setBackground(new java.awt.Color(255, 255, 255));
        boton_Fecha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Fecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/busqueda (1).png"))); // NOI18N
        boton_Fecha.setText("Buscar");
        boton_Fecha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Fecha.setMaximumSize(new java.awt.Dimension(70, 40));
        boton_Fecha.setMinimumSize(new java.awt.Dimension(70, 40));
        boton_Fecha.setPreferredSize(new java.awt.Dimension(70, 40));
        jToolBar2.add(boton_Fecha);
        jToolBar2.add(jSeparator8);

        combo_Opciones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combo_Opciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione.....", "Por numero", "Por nombre", "Por RUC", "Por fecha" }));
        combo_Opciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar2.add(combo_Opciones);

        add(jToolBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 990, 40));

        tabla_Consulta_Compra.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tabla_Consulta_Compra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No_Orden", "Proveedor", "RUC / CI", "Valor", "Fecha", "ID Solicitante", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_Consulta_Compra);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 1290, 760));
    }// </editor-fold>//GEN-END:initComponents

    private void boton_Nueva_Orden_CompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Nueva_Orden_CompraActionPerformed
        
    }//GEN-LAST:event_boton_Nueva_Orden_CompraActionPerformed

    private void boton_Modificar_Orden_CompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Modificar_Orden_CompraActionPerformed
        //this.cantidad_Items.setText(String.valueOf(this.tabla_Productos_Orden_Compra.getRowCount()));
    }//GEN-LAST:event_boton_Modificar_Orden_CompraActionPerformed
 /*
    public void calculo_Valores() {
        try {
            double valor_Subtotal = 0;
            for (int i = 0; i < modelo_Tabla_Datos_Compras.getRowCount(); i++) {
                valor_Subtotal = valor_Subtotal + (double) modelo_Tabla_Datos_Compras.getValueAt(i, 4);
            }
            this.campo_Subtotal_Orden_Compra.setText(this.formato_Numero.format(valor_Subtotal));
            this.campo_IVA_Orden_Compra.setText(this.formato_Numero.format(valor_Subtotal * (Integer)this.valor_IVA.getValue()/100));
            this.campo_Total_Orden_Compra.setText(this.formato_Numero.format(Double.valueOf(this.campo_IVA_Orden_Compra.getText()) + valor_Subtotal));
        } catch (Exception e) {
        }
    }*/
    
 /*   public boolean etiquetas( ){ 
        boolean bandera=true;
        
        if( this.combo_Proveedor_Orden_Compra.getText().isEmpty() ){ 
            this.etiqueta_Indicador_Proveedor.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Proveedor.setVisible( false );
        }
        
        if( this.campo_RUC_Orden_Compra.getText().matches( "[0-9][0-9]{12}" ) ){
            this.etiqueta_Indicador_RUC.setVisible( false );
        }else if(this.campo_RUC_Orden_Compra.getText().matches( "[0-9][0-9]{9}" ) ){
            this.etiqueta_Indicador_RUC.setVisible( false );
        }
        else{
            this.etiqueta_Indicador_RUC.setVisible( true );
            bandera = false;
        }
        
        if (this.calendario_Orden_Compra.getDate() == null) {
            this.etiqueta_Indicador_Calendario.setVisible(bandera);
            bandera = false;
        }else{
            this.etiqueta_Indicador_Calendario.setVisible(false);
        }
            
        if( this.campo_Direccion_Orden_Compra.getText().isEmpty() ){ 
            this.etiqueta_Indicador_Direccion.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Direccion.setVisible( false );
        }
            
        if( this.campo_Telefono_Orden_Compra.getText().matches( "[0][1-9][0-9]{7}" ) ){
            this.etiqueta_Indicador_Telefono.setVisible( false );
        }else{
            this.etiqueta_Indicador_Telefono.setVisible( true );
            bandera = false;
        }  
        
        if( this.campo_Correo_Orden_Compra.getText().matches( "[a-zA-Z_\\d]+@[a-zA-Z]+(\\.[a-zA-Z]*)+" )){  
            this.etiqueta_Indicador_Correo.setVisible( false );
        }else{
            this.etiqueta_Indicador_Correo.setVisible( true );
            bandera = false;
        }
            
        if( this.campo_Solicitante_Orden_Compra.getText().isEmpty() ){
            this.etiqueta_Indicador_Contacto.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Contacto.setVisible( false );
        }
        
        if( this.combo_Modalidad_Pago_Orden_Compra.getSelectedItem().equals( "Seleccionar......" ) ){
            this.etiqueta_Indicador_Modalidad.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Modalidad.setVisible( false );
        }
        
        if (this.combo_Estado_Orden.isVisible()) {
            if (this.combo_Estado_Orden.getSelectedItem().equals("Seleccionar.....")) {
                this.etiqueta_Indicador_Estado.setVisible(true);
                bandera = false;
            } else {
                this.etiqueta_Indicador_Estado.setVisible(false);
            }
        }
        
        return bandera;
    }*/
    /*
    public String[] evaluar_Tabla(){
        DefaultTableModel modelo_Tabla_Cotizacion = (DefaultTableModel) this.tabla_Productos_Orden_Compra.getModel();
        String[] valores = new String[6];

        for (int i = 0; i < modelo_Tabla_Cotizacion.getRowCount(); i++) {
            valores[0] = modelo_Tabla_Cotizacion.getValueAt(i, 0) + ";" + valores[0];
            valores[1] = modelo_Tabla_Cotizacion.getValueAt(i, 1) + ";" + valores[1];
            valores[2] = modelo_Tabla_Cotizacion.getValueAt(i, 2) + ";" + valores[2];
            valores[3] = modelo_Tabla_Cotizacion.getValueAt(i, 3) + ";" + valores[3];
            valores[4] = modelo_Tabla_Cotizacion.getValueAt(i, 4) + ";" + valores[4];
        }
        return valores;
    }*/
    /*
    public String calendario_Fecha() {
        Date fecha;
        fecha = (Date) this.calendario_Orden_Compra.getDate();
        return new SimpleDateFormat("yyyy-MM-dd").format(fecha);
    }*/
   /* 
    public void limpiar_Valores(){
        this.campo_Subtotal_Orden_Compra.setText( "" );
        this.campo_Solicitante_Orden_Compra.setText( "" );
        this.campo_IVA_Orden_Compra.setText( "" );
        this.campo_Total_Orden_Compra.setText( "" );
        this.campo_Solicitante_Orden_Compra.setText( "" );
        this.combo_Modalidad_Pago_Orden_Compra.setSelectedItem( "" );
        this.combo_Proveedor_Orden_Compra.setText("" );
        this.combo_Modalidad_Pago_Orden_Compra.setSelectedItem( "Seleccionar......" );
        this.caja_Observaciones.setText("");
        this.etiqueta_Estado_Orden.setText("");
        this.combo_Estado_Orden.setSelectedItem("Seleccionar.....");
        this.valor_IVA.setValue(12);
    }*/
 /*   
    public void limpiar_Tabla(){
        DefaultTableModel modelo_Tabla_Cotizacion = ( DefaultTableModel ) this.tabla_Productos_Orden_Compra.getModel();
        modelo_Tabla_Cotizacion.setRowCount( 0 );
    }*/
  /*  
    public void botones(boolean bandera1, boolean bandera2, boolean bandera3, boolean bandera4, boolean bandera5, boolean bandera6, boolean bandera7) {
        this.boton_Guardar_Orden_Compra.setEnabled(bandera1);
        this.boton_Buscar_Proveedor_Orden.setEnabled(bandera1);
        this.boton_Nueva_Orden_Compra.setEnabled(bandera2);
        this.boton_Modificar_Orden_Compra.setEnabled(bandera3);
        this.boton_Generar_Orden.setEnabled(bandera4);
        this.combo_Modalidad_Pago_Orden_Compra.setEnabled(bandera5);
        this.boton_Agregar_Fila.setEnabled(bandera6);
        this.boton_Quitar_Fila.setEnabled(bandera6);
        this.combo_Estado_Orden.setEnabled(bandera7);
        this.valor_IVA.setEnabled(bandera6);
    }
  */  
 /*   public void valores_Tabla_Orden(Orden_Compra lista_Orden, Proveedor proveedor) {
        DefaultTableModel modelo_Tabla_Orden = (DefaultTableModel) this.tabla_Productos_Orden_Compra.getModel();
        modelo_Tabla_Orden.setRowCount(0);

        String[] cantidad = lista_Orden.getCantidad().split(";");
        String[] codigo = lista_Orden.getCodigo().split(";");
        String[] descripcion = lista_Orden.getDescripcion().split(";");
        String[] v_Unitario = lista_Orden.getV_Unitario().split(";");
        String[] v_Total = lista_Orden.getV_Total().split(";");

        for (int i = 0; i < codigo.length - 1; i++) {
            Object[] valores_Tabla = {cantidad[i], codigo[i], descripcion[i], Double.parseDouble(v_Unitario[i]), Double.parseDouble(v_Total[i])};
            modelo_Tabla_Orden.addRow(valores_Tabla);
        }
        this.cantidad_Items.setText(String.valueOf(codigo.length - 1));
        this.valores_Proveedores(proveedor.getProveedor(), proveedor.getDireccion(), proveedor.getTelefono(), proveedor.getCorreo(), proveedor.getRUC(), lista_Orden.getSolicitante(), "");
        this.valores_Orden_Compra(lista_Orden.getProveedor(), lista_Orden.getV_Subtotal(), lista_Orden.getIVA(), lista_Orden.getValor_Total(), lista_Orden.getTipo_Pago(), lista_Orden.getNo_Orden(), lista_Orden.getEstado());
    }*/
/*
    public void valores_Orden_Compra(String proveedor, double subtotal, double IVA, double valor_Total, String tipo_Pago, String no_Orden, String estado) {
        this.campo_Subtotal_Orden_Compra.setText(String.valueOf(subtotal));
        this.campo_IVA_Orden_Compra.setText(String.valueOf(IVA));
        this.campo_Total_Orden_Compra.setText(String.valueOf(valor_Total));
        this.combo_Modalidad_Pago_Orden_Compra.setSelectedItem(tipo_Pago);
        this.etiqueta_No_Orden_Compra.setText(no_Orden);
        this.color_Etiqueta_Estado(estado);
        this.valor_IVA.setValue((int)((IVA/subtotal)*100));
    }*/
    
 /*   public void valores_Proveedores(String proveedor, String direccion, String telefono, String correo, String RUC, String nombre, String apellido) {
        this.combo_Proveedor_Orden_Compra.setText(proveedor);
        this.campo_Direccion_Orden_Compra.setText(direccion);
        this.campo_Telefono_Orden_Compra.setText(telefono);
        this.campo_Correo_Orden_Compra.setText(correo);
        this.campo_RUC_Orden_Compra.setText(RUC);
        this.campo_Solicitante_Orden_Compra.setText(nombre + " " + apellido);
    }*/
  /*  
    public void limpiar_Etiquetas() {
        this.etiqueta_Indicador_Proveedor.setVisible(false);
        this.etiqueta_Indicador_RUC.setVisible(false);
        this.etiqueta_Indicador_RUC.setVisible(false);
        this.etiqueta_Indicador_Direccion.setVisible(false);
        this.etiqueta_Indicador_Telefono.setVisible(false);
        this.etiqueta_Indicador_Correo.setVisible(false);
        this.etiqueta_Indicador_Contacto.setVisible(false);
        this.etiqueta_Indicador_Modalidad.setVisible(false);
    }
   */ 
 /*   public void color_Etiqueta_Estado(String estado){
        this.etiqueta_Estado_Orden.setText(estado.toUpperCase());
        
        if(estado.equals("En revision")){
            this.etiqueta_Estado_Orden.setForeground(Color.blue);
        }else if(estado.equals("No Aprobado")){
            this.etiqueta_Estado_Orden.setForeground(Color.RED);
        }else if(estado.equals("Aprobado")){
            this.etiqueta_Estado_Orden.setForeground(Color.GREEN);
        }else if(estado.equals("Anulado")){
            this.etiqueta_Estado_Orden.setForeground(Color.BLACK);
        }
    }*/
    
    public void desactivar_Calendarios(boolean bandera) {
        this.fecha_1.setVisible(bandera);
        this.fecha_2.setVisible(bandera);
        this.boton_Fecha.setVisible(bandera);
    }

    public boolean verificar_Campos() {
        boolean bandera = true;

        if (this.fecha_1.getDate() == null) {
            bandera = false;
        }

        if (this.fecha_2.getDate() == null) {
            bandera = false;
        }

        return bandera;
    }

    public String calendario_Inicio() {
        Date fecha = this.fecha_1.getDate();
        return new SimpleDateFormat("yyyy-MM-dd").format(fecha);
    }

    public String calendario_Final() {
        Date fecha = this.fecha_2.getDate();
        return new SimpleDateFormat("yyyy-MM-dd").format(fecha);
    }
    
     public void etiqueta_Error_Etiqueta(boolean bandera){
        this.etiqueta_Error_Fecha.setVisible(bandera);
    }
    
    public void set_Usuario(Usuario usuario, String rol){
        this.etiqueta_Nombre_Usuario.setText(usuario.getNombre() + " " + usuario.getApellido());
        this.etiqueta_Rol.setText(rol);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton boton_Cerrar_Sesion;
    public javax.swing.JButton boton_Fecha;
    public javax.swing.JButton boton_Generar_Orden;
    public javax.swing.JButton boton_Modificar_Orden_Compra;
    public javax.swing.JButton boton_Nueva_Orden_Compra;
    public javax.swing.JTextField campo_Busqueda;
    public javax.swing.JComboBox<String> combo_Opciones;
    public javax.swing.JLabel etiqueta_Error_Fecha;
    public javax.swing.JLabel etiqueta_Nombre_Usuario;
    public javax.swing.JLabel etiqueta_Rol;
    public com.toedter.calendar.JDateChooser fecha_1;
    public com.toedter.calendar.JDateChooser fecha_2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    public javax.swing.JTable tabla_Consulta_Compra;
    // End of variables declaration//GEN-END:variables

}
