/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Cotizacion;

import Modelo.Cliente;
import Modelo.Cotizacion;
import Modelo.Usuario;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David
 */
public class Dialogo_Cotizacion extends javax.swing.JDialog {
    private final DefaultTableModel       modelo_Tabla_Datos_Cotizacion;
    private final DecimalFormat           formato_Numero = new DecimalFormat("#.00", new DecimalFormatSymbols(Locale.US));
    /**
     * Creates new form Dialogo_Cotizacion
     */
    public Dialogo_Cotizacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.etiqueta_Indicador_Cliente.setVisible(false);
        this.etiqueta_Indicador_Ciudad.setVisible(false);
        this.etiqueta_Indicador_RUC.setVisible(false);
        this.etiqueta_Indicador_Direccion.setVisible(false);
        this.etiqueta_Indicador_Telefono.setVisible(false);
        this.etiqueta_Indicador_Correo.setVisible(false);
        this.etiqueta_Indicador_Contacto.setVisible(false);
        this.etiqueta_Indicador_Modalidad.setVisible(false);
        this.etiqueta_Indicador_Calendario.setVisible(false);
        this.modelo_Tabla_Datos_Cotizacion = (DefaultTableModel) this.tabla_Productos_Cotizacion.getModel();
        this.tabla_Productos_Cotizacion.getTableHeader().setReorderingAllowed(false) ;
        this.boton_Agregar_Fila.setEnabled(false);
        this.boton_Quitar_Fila.setEnabled(false);
        this.calendario_Cotizacion.setDate(new Date());
        this.valor_IVA.setValue(12);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calendario_Cotizacion = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        campo_Direccion_Cotizacion = new javax.swing.JTextField();
        campo_Contacto_Cotizacion = new javax.swing.JTextField();
        campo_Correo_Cotizacion = new javax.swing.JTextField();
        campo_Telefono_Cotizacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Productos_Cotizacion = new javax.swing.JTable();
        campo_Subtotal_Cotizacion = new javax.swing.JTextField();
        campo_IVA_Cotizacion = new javax.swing.JTextField();
        campo_Total_Cotizacion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        campo_Modalidad_Cotizacion = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        etiqueta_No_Cotizacion = new javax.swing.JLabel();
        boton_Agregar_Fila = new javax.swing.JButton();
        boton_Quitar_Fila = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        campo_RUC_Cotizacion = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        campo_Ciudad_Cotizacion = new javax.swing.JTextField();
        etiqueta_Indicador_Cliente = new javax.swing.JLabel();
        etiqueta_Indicador_Direccion = new javax.swing.JLabel();
        etiqueta_Indicador_Telefono = new javax.swing.JLabel();
        etiqueta_Indicador_Ciudad = new javax.swing.JLabel();
        etiqueta_Indicador_Correo = new javax.swing.JLabel();
        etiqueta_Indicador_RUC = new javax.swing.JLabel();
        etiqueta_Indicador_Contacto = new javax.swing.JLabel();
        etiqueta_Indicador_Modalidad = new javax.swing.JLabel();
        combo_Cliente_Cotizacion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        campo_Emisor_Cotizacion = new javax.swing.JTextField();
        campo_Codigo_Cliente = new javax.swing.JTextField();
        etiqueta_Indicador_Calendario = new javax.swing.JLabel();
        valor_IVA = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        boton_Guardar_Cotizacion = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        boton_Agregar_Cliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1060, 760));
        setMinimumSize(new java.awt.Dimension(1060, 760));
        setPreferredSize(new java.awt.Dimension(1060, 760));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        calendario_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        calendario_Cotizacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        calendario_Cotizacion.setDateFormatString("yyyy-MM-dd");
        calendario_Cotizacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(calendario_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 68, 160, 24));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel3.setText("Fecha:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel5.setText("Cliente:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Direccion:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 271, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Telefono:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 192, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Solicitante:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 232, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Correo:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 272, -1, -1));

        campo_Direccion_Cotizacion.setEditable(false);
        campo_Direccion_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        campo_Direccion_Cotizacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Direccion_Cotizacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Direccion_Cotizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Direccion_CotizacionKeyTyped(evt);
            }
        });
        getContentPane().add(campo_Direccion_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 310, 24));

        campo_Contacto_Cotizacion.setEditable(false);
        campo_Contacto_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        campo_Contacto_Cotizacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Contacto_Cotizacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Contacto_Cotizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Contacto_CotizacionKeyTyped(evt);
            }
        });
        getContentPane().add(campo_Contacto_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 280, 24));

        campo_Correo_Cotizacion.setEditable(false);
        campo_Correo_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        campo_Correo_Cotizacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Correo_Cotizacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Correo_Cotizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Correo_CotizacionKeyTyped(evt);
            }
        });
        getContentPane().add(campo_Correo_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 300, 24));

        campo_Telefono_Cotizacion.setEditable(false);
        campo_Telefono_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        campo_Telefono_Cotizacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Telefono_Cotizacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Telefono_Cotizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Telefono_CotizacionKeyTyped(evt);
            }
        });
        getContentPane().add(campo_Telefono_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 150, 24));

        tabla_Productos_Cotizacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tabla_Productos_Cotizacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cant", "Codigo", "Descripcion", "V. Unitario", "V. Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_Productos_Cotizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tabla_Productos_CotizacionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_Productos_Cotizacion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 830, 240));

        campo_Subtotal_Cotizacion.setEditable(false);
        campo_Subtotal_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        campo_Subtotal_Cotizacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Subtotal_Cotizacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(campo_Subtotal_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 630, 100, 23));

        campo_IVA_Cotizacion.setEditable(false);
        campo_IVA_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        campo_IVA_Cotizacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_IVA_Cotizacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(campo_IVA_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 660, 100, 23));

        campo_Total_Cotizacion.setEditable(false);
        campo_Total_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        campo_Total_Cotizacion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        campo_Total_Cotizacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(campo_Total_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 690, 100, 23));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Subtotal:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 630, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("IVA:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 660, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Total:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 690, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Modalidad de pago:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, -1, -1));

        campo_Modalidad_Cotizacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Modalidad_Cotizacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Modalidad_Cotizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Modalidad_CotizacionKeyTyped(evt);
            }
        });
        getContentPane().add(campo_Modalidad_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 630, 200, 24));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel15.setText("No. Cotizacion:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        etiqueta_No_Cotizacion.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        etiqueta_No_Cotizacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(etiqueta_No_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 68, 170, 24));

        boton_Agregar_Fila.setBackground(new java.awt.Color(255, 255, 255));
        boton_Agregar_Fila.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Agregar_Fila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mas (1).png"))); // NOI18N
        boton_Agregar_Fila.setText("Agregar producto");
        boton_Agregar_Fila.setToolTipText("Agregar");
        boton_Agregar_Fila.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(boton_Agregar_Fila, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 420, 140, -1));

        boton_Quitar_Fila.setBackground(new java.awt.Color(255, 255, 255));
        boton_Quitar_Fila.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Quitar_Fila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menos.png"))); // NOI18N
        boton_Quitar_Fila.setText("Quitar producto");
        boton_Quitar_Fila.setToolTipText("Quitar");
        boton_Quitar_Fila.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Quitar_Fila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Quitar_FilaActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Quitar_Fila, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 470, 140, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel16.setText("RUC:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 150, -1, -1));

        campo_RUC_Cotizacion.setEditable(false);
        campo_RUC_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        campo_RUC_Cotizacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_RUC_Cotizacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_RUC_Cotizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_RUC_CotizacionKeyTyped(evt);
            }
        });
        getContentPane().add(campo_RUC_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 230, 24));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel18.setText("Ciudad:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 192, -1, -1));

        campo_Ciudad_Cotizacion.setEditable(false);
        campo_Ciudad_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        campo_Ciudad_Cotizacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Ciudad_Cotizacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Ciudad_Cotizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_Ciudad_CotizacionKeyTyped(evt);
            }
        });
        getContentPane().add(campo_Ciudad_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 230, 24));

        etiqueta_Indicador_Cliente.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Cliente.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Cliente.setText("*");
        getContentPane().add(etiqueta_Indicador_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 146, -1, -1));

        etiqueta_Indicador_Direccion.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Direccion.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Direccion.setText("*");
        getContentPane().add(etiqueta_Indicador_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 265, -1, -1));

        etiqueta_Indicador_Telefono.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Telefono.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Telefono.setText("*");
        getContentPane().add(etiqueta_Indicador_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 187, -1, -1));

        etiqueta_Indicador_Ciudad.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Ciudad.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Ciudad.setText("*");
        getContentPane().add(etiqueta_Indicador_Ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 187, -1, -1));

        etiqueta_Indicador_Correo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Correo.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Correo.setText("*");
        getContentPane().add(etiqueta_Indicador_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 265, 20, -1));

        etiqueta_Indicador_RUC.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_RUC.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_RUC.setText("*");
        getContentPane().add(etiqueta_Indicador_RUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 146, -1, -1));

        etiqueta_Indicador_Contacto.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Contacto.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Contacto.setText("*");
        getContentPane().add(etiqueta_Indicador_Contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 228, -1, -1));

        etiqueta_Indicador_Modalidad.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Modalidad.setForeground(new java.awt.Color(198, 0, 0));
        etiqueta_Indicador_Modalidad.setText("*");
        getContentPane().add(etiqueta_Indicador_Modalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 630, -1, -1));

        combo_Cliente_Cotizacion.setEditable(false);
        combo_Cliente_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        combo_Cliente_Cotizacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combo_Cliente_Cotizacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(combo_Cliente_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 230, 24));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Emite:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 232, -1, -1));

        campo_Emisor_Cotizacion.setEditable(false);
        campo_Emisor_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        campo_Emisor_Cotizacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Emisor_Cotizacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Emisor_Cotizacion.setMaximumSize(new java.awt.Dimension(2, 20));
        campo_Emisor_Cotizacion.setMinimumSize(new java.awt.Dimension(2, 20));
        campo_Emisor_Cotizacion.setPreferredSize(new java.awt.Dimension(2, 20));
        getContentPane().add(campo_Emisor_Cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 230, 24));

        campo_Codigo_Cliente.setEditable(false);
        campo_Codigo_Cliente.setBackground(new java.awt.Color(255, 255, 255));
        campo_Codigo_Cliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_Codigo_Cliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(campo_Codigo_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 100, 24));

        etiqueta_Indicador_Calendario.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        etiqueta_Indicador_Calendario.setForeground(new java.awt.Color(220, 0, 0));
        etiqueta_Indicador_Calendario.setText("*");
        getContentPane().add(etiqueta_Indicador_Calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 20, -1));

        valor_IVA.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        valor_IVA.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        valor_IVA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                valor_IVAStateChanged(evt);
            }
        });
        valor_IVA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valor_IVAKeyTyped(evt);
            }
        });
        getContentPane().add(valor_IVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 670, 110, 24));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel20.setText("IVA %:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 672, -1, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Valor total", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 1030, 130));

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Informacion cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1030, 200));

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 1030, 270));

        jLabel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1030, 40));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        boton_Guardar_Cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        boton_Guardar_Cotizacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Guardar_Cotizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/businessapplication_accept_ok_male_man_you_negocio_2311.png"))); // NOI18N
        boton_Guardar_Cotizacion.setText("Guardar");
        boton_Guardar_Cotizacion.setToolTipText("Guardar cotizacion");
        boton_Guardar_Cotizacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Guardar_Cotizacion.setFocusable(false);
        boton_Guardar_Cotizacion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_Guardar_Cotizacion.setMaximumSize(new java.awt.Dimension(110, 37));
        boton_Guardar_Cotizacion.setMinimumSize(new java.awt.Dimension(110, 37));
        boton_Guardar_Cotizacion.setPreferredSize(new java.awt.Dimension(110, 37));
        jToolBar1.add(boton_Guardar_Cotizacion);
        jToolBar1.add(jSeparator1);

        boton_Agregar_Cliente.setBackground(new java.awt.Color(255, 255, 255));
        boton_Agregar_Cliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Agregar_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/business_man_usersearch_thesearch_theclient_2356.png"))); // NOI18N
        boton_Agregar_Cliente.setText("Cliente");
        boton_Agregar_Cliente.setToolTipText("Agregar cliente");
        boton_Agregar_Cliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Agregar_Cliente.setMaximumSize(new java.awt.Dimension(85, 37));
        boton_Agregar_Cliente.setMinimumSize(new java.awt.Dimension(85, 37));
        boton_Agregar_Cliente.setPreferredSize(new java.awt.Dimension(85, 37));
        jToolBar1.add(boton_Agregar_Cliente);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 1060, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campo_Direccion_CotizacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Direccion_CotizacionKeyTyped
        char c = evt.getKeyChar();
        if (c == evt.VK_SPACE && this.campo_Direccion_Cotizacion.getText().length() == 0) {
            evt.consume();
        } else if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < '0' || c > '9') && (c < '-' || c > '.') && c != evt.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_campo_Direccion_CotizacionKeyTyped

    private void campo_Contacto_CotizacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Contacto_CotizacionKeyTyped
        char c = evt.getKeyChar();
        if (c == evt.VK_SPACE && this.campo_Contacto_Cotizacion.getText().length() == 0) {
            evt.consume();
        } else if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && c != evt.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_campo_Contacto_CotizacionKeyTyped

    private void campo_Correo_CotizacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Correo_CotizacionKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < '0' || c > '9') && (c < '#' || c > '&') && (c < '-' || c > '/') && (c == evt.VK_SPACE || this.campo_Correo_Cotizacion.getText().contains("@"))) {
            evt.consume();
        }
    }//GEN-LAST:event_campo_Correo_CotizacionKeyTyped

    private void campo_Telefono_CotizacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Telefono_CotizacionKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9' || this.campo_Telefono_Cotizacion.getText().length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_campo_Telefono_CotizacionKeyTyped

    private void tabla_Productos_CotizacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_Productos_CotizacionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tabla_Productos_CotizacionKeyTyped

    private void campo_Modalidad_CotizacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Modalidad_CotizacionKeyTyped
        char c = evt.getKeyChar();
        if (c == evt.VK_SPACE && this.campo_Modalidad_Cotizacion.getText().length() == 0) {
            evt.consume();
        } else if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < '0' || c > '9') && c != evt.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_campo_Modalidad_CotizacionKeyTyped

    private void boton_Quitar_FilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Quitar_FilaActionPerformed
        try {
            this.modelo_Tabla_Datos_Cotizacion.removeRow(this.tabla_Productos_Cotizacion.getSelectedRow());
            calculo_Valores();
        } catch (Exception e1) {
        }
    }//GEN-LAST:event_boton_Quitar_FilaActionPerformed

    private void campo_RUC_CotizacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_RUC_CotizacionKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9' || this.campo_RUC_Cotizacion.getText().length() >= 13) {
            evt.consume();
        }
    }//GEN-LAST:event_campo_RUC_CotizacionKeyTyped

    private void campo_Ciudad_CotizacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_Ciudad_CotizacionKeyTyped
        char c = evt.getKeyChar();
        if (c == evt.VK_SPACE && this.campo_Ciudad_Cotizacion.getText().length() == 0) {
            evt.consume();
        } else if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && c != evt.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_campo_Ciudad_CotizacionKeyTyped

    private void valor_IVAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_valor_IVAStateChanged
        if ((Integer) this.valor_IVA.getValue() < 1) {
            this.valor_IVA.setValue(1);
        } else if ((Integer) this.valor_IVA.getValue() > 25) {
            this.valor_IVA.setValue(25);
        } else {
            calculo_Valores();
        }
    }//GEN-LAST:event_valor_IVAStateChanged

    private void valor_IVAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valor_IVAKeyTyped

    }//GEN-LAST:event_valor_IVAKeyTyped

    public boolean etiquetas( ){
        boolean bandera = true;
        
        if( this.combo_Cliente_Cotizacion.getText().isEmpty() ){
            this.etiqueta_Indicador_Cliente.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Cliente.setVisible( false );
        }
        
        if( this.campo_Ciudad_Cotizacion.getText().isEmpty() ){
            this.etiqueta_Indicador_Ciudad.setVisible( true );
            bandera = false;
        }else{ 
           this.etiqueta_Indicador_Ciudad.setVisible( false );
        }
            
        if( this.campo_RUC_Cotizacion.getText().matches( "[0-9][0-9]{12}" ) ){
            this.etiqueta_Indicador_RUC.setVisible( false );
        }else if(this.campo_RUC_Cotizacion.getText().matches( "[0-9][0-9]{9}" ) ){
            this.etiqueta_Indicador_RUC.setVisible( false );
        }
        else{
            this.etiqueta_Indicador_RUC.setVisible( true );
            bandera = false;
        }
            
        if( this.campo_Direccion_Cotizacion.getText().isEmpty() ){ 
            this.etiqueta_Indicador_Direccion.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Direccion.setVisible( false );
        }
            
        if (this.campo_Telefono_Cotizacion.getText().matches("[0][1-9][0-9]{7}|[0][8-9][0-9]{8}")) {
            this.etiqueta_Indicador_Telefono.setVisible(false);
        } else {
            this.etiqueta_Indicador_Telefono.setVisible(true);
            bandera = false;
        }
        
        if (this.calendario_Cotizacion.getDate() == null) {
            this.etiqueta_Indicador_Calendario.setVisible(bandera);
            bandera = false;
        }else{
            this.etiqueta_Indicador_Calendario.setVisible(false);
        }
        
        if( this.campo_Correo_Cotizacion.getText().matches( "[a-zA-Z_\\d]+@[a-zA-Z]+(\\.[a-zA-Z]*)+" )){  
            this.etiqueta_Indicador_Correo.setVisible( false );
        }else{
            this.etiqueta_Indicador_Correo.setVisible( true );
            bandera = false;
        }
            
        if( this.campo_Contacto_Cotizacion.getText().isEmpty() ){
            this.etiqueta_Indicador_Contacto.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Contacto.setVisible( false );
        }
        
        if( this.campo_Modalidad_Cotizacion.getText().isEmpty() ){
            this.etiqueta_Indicador_Modalidad.setVisible( true );
            bandera = false;
        }else{ 
            this.etiqueta_Indicador_Modalidad.setVisible( false );
        }
        return bandera;
    }
    
    public void valores_Tabla_Cotizacion(Cotizacion lista_Cotizacion, Cliente cliente, Usuario usuario) {
        this.modelo_Tabla_Datos_Cotizacion.setRowCount(0);

        String[] cantidad = lista_Cotizacion.getCantidad().split(";");
        String[] codigo = lista_Cotizacion.getCodigo().split(";");
        String[] descripcion = lista_Cotizacion.getDescripcion().split(";");
        String[] v_Unitario = lista_Cotizacion.getV_Unitario().split(";");
        String[] v_Total = lista_Cotizacion.getV_Total().split(";");

        for (int i = 0; i < codigo.length - 1; i++) {
            Object[] valores_Tabla = {cantidad[i], codigo[i], descripcion[i], Double.parseDouble(v_Unitario[i]), Double.parseDouble(v_Total[i])};
            this.modelo_Tabla_Datos_Cotizacion.addRow(valores_Tabla);
        }

        this.valores_Clientes(cliente, usuario);
        this.valores_Cotizacion(lista_Cotizacion);
    }
    
    public void valores_Cotizacion(Cotizacion cotizacion) {
        this.campo_Subtotal_Cotizacion.setText(String.valueOf(cotizacion.getV_Subtotal()));
        this.campo_IVA_Cotizacion.setText(String.valueOf(cotizacion.getIVA()));
        this.campo_Total_Cotizacion.setText(String.valueOf(cotizacion.getValor_Total()));
        this.campo_Modalidad_Cotizacion.setText(cotizacion.getTipo_Pago());
        this.etiqueta_No_Cotizacion.setText(cotizacion.getNo_Cotizacion());
        this.valor_IVA.setValue((int) ((cotizacion.getIVA() / cotizacion.getV_Subtotal()) * 100));
    }

    public void valores_Clientes(Cliente cliente, Usuario usuario) {
        this.campo_Codigo_Cliente.setText(cliente.getCodigo_Cliente());
        this.combo_Cliente_Cotizacion.setText(cliente.getCliente());
        this.campo_Direccion_Cotizacion.setText(cliente.getDireccion());
        this.campo_Telefono_Cotizacion.setText(cliente.getTelefono());
        this.campo_Correo_Cotizacion.setText(cliente.getCorreo());
        this.campo_RUC_Cotizacion.setText(cliente.getRUC());
        this.campo_Ciudad_Cotizacion.setText(cliente.getCiudad());
        this.campo_Contacto_Cotizacion.setText(cliente.getPersona_Contacto());
        this.campo_Emisor_Cotizacion.setText(usuario.getNombre() + " " + usuario.getApellido());
    }
    
    public void calculo_Valores() {
        try {
            double valor_Subtotal = 0;
            for (int i = 0; i < this.modelo_Tabla_Datos_Cotizacion.getRowCount(); i++) {
                valor_Subtotal = valor_Subtotal + (double) this.modelo_Tabla_Datos_Cotizacion.getValueAt(i, 4);
            }
            this.campo_Subtotal_Cotizacion.setText(this.formato_Numero.format(valor_Subtotal));
            this.campo_IVA_Cotizacion.setText(this.formato_Numero.format(valor_Subtotal * (Integer) this.valor_IVA.getValue() / 100));
            this.campo_Total_Cotizacion.setText(this.formato_Numero.format(Double.valueOf(this.campo_IVA_Cotizacion.getText()) + valor_Subtotal));
        } catch (Exception e) {
        }
    }
    
    public String[] evaluar_Tabla() {
        DefaultTableModel modelo_Tabla_Cotizacion = (DefaultTableModel) this.tabla_Productos_Cotizacion.getModel();
        String[] valores = new String[6];

        for (int i = 0; i < modelo_Tabla_Cotizacion.getRowCount(); i++) {
            valores[0] = modelo_Tabla_Cotizacion.getValueAt(i, 0) + ";" + valores[0];
            valores[1] = modelo_Tabla_Cotizacion.getValueAt(i, 1) + ";" + valores[1];
            valores[2] = modelo_Tabla_Cotizacion.getValueAt(i, 2) + ";" + valores[2];
            valores[3] = modelo_Tabla_Cotizacion.getValueAt(i, 3) + ";" + valores[3];
            valores[4] = modelo_Tabla_Cotizacion.getValueAt(i, 4) + ";" + valores[4];
        }
        return valores;
    }
    
    public String calendario_Fecha() {
        Date fecha;
        fecha = (Date) this.calendario_Cotizacion.getDate();
        return new SimpleDateFormat("yyyy-MM-dd").format(fecha);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dialogo_Cotizacion dialog = new Dialogo_Cotizacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton boton_Agregar_Cliente;
    public javax.swing.JButton boton_Agregar_Fila;
    public javax.swing.JButton boton_Guardar_Cotizacion;
    public javax.swing.JButton boton_Quitar_Fila;
    public com.toedter.calendar.JDateChooser calendario_Cotizacion;
    public javax.swing.JTextField campo_Ciudad_Cotizacion;
    public javax.swing.JTextField campo_Codigo_Cliente;
    public javax.swing.JTextField campo_Contacto_Cotizacion;
    public javax.swing.JTextField campo_Correo_Cotizacion;
    public javax.swing.JTextField campo_Direccion_Cotizacion;
    public javax.swing.JTextField campo_Emisor_Cotizacion;
    public javax.swing.JTextField campo_IVA_Cotizacion;
    public javax.swing.JTextField campo_Modalidad_Cotizacion;
    public javax.swing.JTextField campo_RUC_Cotizacion;
    public javax.swing.JTextField campo_Subtotal_Cotizacion;
    public javax.swing.JTextField campo_Telefono_Cotizacion;
    public javax.swing.JTextField campo_Total_Cotizacion;
    public javax.swing.JTextField combo_Cliente_Cotizacion;
    private javax.swing.JLabel etiqueta_Indicador_Calendario;
    private javax.swing.JLabel etiqueta_Indicador_Ciudad;
    private javax.swing.JLabel etiqueta_Indicador_Cliente;
    private javax.swing.JLabel etiqueta_Indicador_Contacto;
    private javax.swing.JLabel etiqueta_Indicador_Correo;
    private javax.swing.JLabel etiqueta_Indicador_Direccion;
    private javax.swing.JLabel etiqueta_Indicador_Modalidad;
    private javax.swing.JLabel etiqueta_Indicador_RUC;
    private javax.swing.JLabel etiqueta_Indicador_Telefono;
    public javax.swing.JLabel etiqueta_No_Cotizacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    public javax.swing.JTable tabla_Productos_Cotizacion;
    public javax.swing.JSpinner valor_IVA;
    // End of variables declaration//GEN-END:variables
}
