/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Maquilas;

import Modelo.Usuario;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author David
 */
public class Panel_Maquilas extends javax.swing.JPanel {
    private TableRowSorter                TRSFiltro;

    /**
     * Creates new form Panel_Maquila
     */
    public Panel_Maquilas() {
        initComponents();
        this.tabla_Maquilas.getTableHeader().setReorderingAllowed(false) ;
        this.campo_Buscar.setEditable(false);
        this.boton_Modificar.setEnabled( false );
        this.boton_Eliminar.setEnabled( false );
    }

    public void Roles(String rol) {
        if (rol.equals("Vendedor")) {
            boolean[] bandera = {false, false, false, false, false, false};
            this.habilitar_Rol(bandera);
        }

        if (rol.equals("Bodeguero")) {
            boolean[] bandera = {false, false, false, false, false, false};
            this.habilitar_Rol(bandera);
        }

        if (rol.equals("Contador")) {
            boolean[] bandera = {false, false, false, true, false, false};
            this.habilitar_Rol(bandera);
        }

        if (rol.equals("Administrador")) {
            boolean[] bandera = {false, false, false, false, false, false};
            this.habilitar_Rol(bandera);
        }
        
        if (rol.equals("Maquila")) {
            boolean[] bandera = {true, true, true, true, true, true};
            this.habilitar_Rol(bandera);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        boton_Nuevo_Maquila = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        boton_Modificar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        boton_Eliminar = new javax.swing.JButton();
        boton_Cerrar_Sesion = new javax.swing.JButton();
        etiqueta_Rol = new javax.swing.JLabel();
        etiqueta_Nombre_Usuario = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        campo_Buscar = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        combo_Opciones = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Maquilas = new javax.swing.JTable();

        setBackground(new java.awt.Color(239, 239, 239));
        setMaximumSize(new java.awt.Dimension(1400, 800));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setPreferredSize(new java.awt.Dimension(1400, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        boton_Nuevo_Maquila.setBackground(new java.awt.Color(255, 255, 255));
        boton_Nuevo_Maquila.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Nuevo_Maquila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/maquila add.png"))); // NOI18N
        boton_Nuevo_Maquila.setText("Nuevo");
        boton_Nuevo_Maquila.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Nuevo_Maquila.setFocusable(false);
        boton_Nuevo_Maquila.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_Nuevo_Maquila.setMaximumSize(new java.awt.Dimension(80, 52));
        boton_Nuevo_Maquila.setMinimumSize(new java.awt.Dimension(120, 52));
        boton_Nuevo_Maquila.setPreferredSize(new java.awt.Dimension(120, 42));
        boton_Nuevo_Maquila.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        boton_Nuevo_Maquila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Nuevo_MaquilaActionPerformed(evt);
            }
        });
        jToolBar1.add(boton_Nuevo_Maquila);
        jToolBar1.add(jSeparator1);
        jToolBar1.add(jSeparator2);

        boton_Modificar.setBackground(java.awt.Color.white);
        boton_Modificar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/maquila mod.png"))); // NOI18N
        boton_Modificar.setText("Modificar");
        boton_Modificar.setToolTipText(" Editar");
        boton_Modificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_Modificar.setMaximumSize(new java.awt.Dimension(80, 52));
        boton_Modificar.setMinimumSize(new java.awt.Dimension(120, 42));
        boton_Modificar.setPreferredSize(new java.awt.Dimension(120, 42));
        boton_Modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(boton_Modificar);
        jToolBar1.add(jSeparator3);

        boton_Eliminar.setBackground(java.awt.Color.white);
        boton_Eliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/maquila elimi.png"))); // NOI18N
        boton_Eliminar.setText("Eliminar");
        boton_Eliminar.setToolTipText("Eliminar");
        boton_Eliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_Eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_Eliminar.setMaximumSize(new java.awt.Dimension(80, 52));
        boton_Eliminar.setMinimumSize(new java.awt.Dimension(120, 42));
        boton_Eliminar.setPreferredSize(new java.awt.Dimension(120, 42));
        boton_Eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(boton_Eliminar);

        add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 800));

        boton_Cerrar_Sesion.setBackground(new java.awt.Color(255, 255, 255));
        boton_Cerrar_Sesion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        boton_Cerrar_Sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exit-32.png"))); // NOI18N
        boton_Cerrar_Sesion.setText("Cerrar");
        boton_Cerrar_Sesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(boton_Cerrar_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 120, 40));

        etiqueta_Rol.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        etiqueta_Rol.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(etiqueta_Rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(1134, 20, 147, 20));

        etiqueta_Nombre_Usuario.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        etiqueta_Nombre_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        etiqueta_Nombre_Usuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        etiqueta_Nombre_Usuario.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(etiqueta_Nombre_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 180, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo blanco.png"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 180, 40));

        jToolBar2.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        jLabel1.setText("    ");
        jToolBar2.add(jLabel1);

        campo_Buscar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        campo_Buscar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campo_Buscar.setMaximumSize(new java.awt.Dimension(750, 30));
        campo_Buscar.setMinimumSize(new java.awt.Dimension(750, 30));
        campo_Buscar.setPreferredSize(new java.awt.Dimension(730, 30));
        campo_Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_BuscarKeyTyped(evt);
            }
        });
        jToolBar2.add(campo_Buscar);
        jToolBar2.add(jSeparator4);

        combo_Opciones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combo_Opciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione.....", "Por nombre", "Por RUC / CI", "Por servicio" }));
        combo_Opciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar2.add(combo_Opciones);

        add(jToolBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 1020, 40));

        tabla_Maquilas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Maquila", "Nombre", "RUC/ CI", "Servicios", "Direccion", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_Maquilas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_MaquilasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_Maquilas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 1320, 760));
    }// </editor-fold>//GEN-END:initComponents

    private void boton_Nuevo_MaquilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Nuevo_MaquilaActionPerformed

    }//GEN-LAST:event_boton_Nuevo_MaquilaActionPerformed

    private void campo_BuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_BuscarKeyTyped
if (this.combo_Opciones.getSelectedItem().equals("Seleccionar.....")) {
            this.campo_Buscar.setEditable(false);
        } else {
            this.campo_Buscar.setEditable(true);
            if (evt.getSource() == this.campo_Buscar) {
                this.campo_Buscar.addKeyListener(new KeyAdapter() {

                    public void keyReleased(final KeyEvent e) {
                        filtro();
                    }
                });

                TRSFiltro = new TableRowSorter(this.tabla_Maquilas.getModel());
                this.tabla_Maquilas.setRowSorter(TRSFiltro);
            }
        }
    }//GEN-LAST:event_campo_BuscarKeyTyped

    private void tabla_MaquilasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_MaquilasMouseClicked
        seleccion_Tabla(this.tabla_Maquilas.getSelectedRow());
    }//GEN-LAST:event_tabla_MaquilasMouseClicked

    public void filtro() {
        if (this.combo_Opciones.getSelectedItem() == "Por nombre") {
            filtrar_Tabla(1);
        } else if (this.combo_Opciones.getSelectedItem() == "Por RUC / CI") {
            filtrar_Tabla(2);
        } else if (this.combo_Opciones.getSelectedItem() == "Por servicio") {
            filtrar_Tabla(3);
        }
    }

    public void filtrar_Tabla(int valor) {
        seleccion_Tabla(this.tabla_Maquilas.getSelectedRow());
        TRSFiltro.setRowFilter(RowFilter.regexFilter("(?i)" + this.campo_Buscar.getText(), valor));
    }

    public void seleccion_Tabla(int bandera) {
        if (bandera != -1) {
            this.boton_Modificar.setEnabled(true);
            this.boton_Eliminar.setEnabled(true);
        } else {
            this.boton_Modificar.setEnabled(false);
            this.boton_Eliminar.setEnabled(false);
        }
    }
    
    public void set_Usuario(Usuario usuario, String rol) {
        this.etiqueta_Nombre_Usuario.setText(usuario.getNombre() + " " + usuario.getApellido());
        this.etiqueta_Rol.setText(rol);
    }

    public void habilitar_Rol(boolean[] bandera) {
        this.boton_Nuevo_Maquila.setVisible(bandera[0]);
        this.boton_Modificar.setVisible(bandera[1]);
        this.boton_Eliminar.setVisible(bandera[2]);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton boton_Cerrar_Sesion;
    public javax.swing.JButton boton_Eliminar;
    public javax.swing.JButton boton_Modificar;
    public javax.swing.JButton boton_Nuevo_Maquila;
    public javax.swing.JTextField campo_Buscar;
    public javax.swing.JComboBox<String> combo_Opciones;
    public javax.swing.JLabel etiqueta_Nombre_Usuario;
    public javax.swing.JLabel etiqueta_Rol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    public javax.swing.JTable tabla_Maquilas;
    // End of variables declaration//GEN-END:variables
}
